### ISSUE TITLE
Cannot find OpenEye toolkit ...

### ISSUE THREAD

**Issue by earnoult** [choderalab/yank#1022]
Hi,
Compounds from a project are too large for SQM to converge, so decided to give a try with quacpac to compute am1-bcc charges using this YAML script.

#
# June 2018
#
```
options:
  minimize: yes
  verbose: yes
  number_of_iterations: 5000 # default 500
  temperature: 300*kelvin
  pressure: 1*atmosphere # To run with NVT ensemble, set this option to "null". Defaults to 1 atm if excluded
  platform: CUDA
  output_dir: project-explicit-CUDA-output

molecules:

  project:
    filepath: input/project.pdb

  EXT:
    filepath: input/EXT.mol2
    antechamber:
      charge_method: null
    openeye:
      quacpac: am1-bcc
[...]
```
when running the script, I get this error message, related to the OETK:
```
"Cannot find OpenEye toolkit with OEChem and OEQuacPac to compute charges for molecule EXT"
```
How do I define the OE env to point to the OETK in a YAML script? or is it inherited from the shell ?

thanks
Eric
