### ISSUE TITLE
discontinuity in the energies at restart

### ISSUE THREAD

**Issue by isjoung** [choderalab/yank#1079]
Hi,
I experience weird energy jumps at restart.
![l4](https://user-images.githubusercontent.com/7530585/44644565-8ce74c00-aa0f-11e8-8a88-78b1bb94819c.png)
![l10](https://user-images.githubusercontent.com/7530585/44644569-8f49a600-aa0f-11e8-970c-a72d092befb0.png)
![l13](https://user-images.githubusercontent.com/7530585/44644573-91136980-aa0f-11e8-9510-171e1e99a9a2.png)
I restarted runs at 1100 steps and 1700 steps. In a few cases, I see energy jumps. It looks apparent at solvent simulations. I am not sure this also occurs in the complex phase. But, visually I don't see such obvious discontinuity in the complex phase.
Does anybody know what could be the source of the problem?

yank version is 0.23.3. GPU is Tesla V100.

This is my input script
```yaml
options:
  resume_setup: yes
  resume_simulation: yes
  minimize: yes
  verbose: yes
  default_number_of_iterations: 1700
  default_nsteps_per_iteration: 500
  temperature: 300*kelvin
  pressure: 1*atmosphere
  checkpoint_interval: 50
  platform: CUDA
  output_dir: fep

solvents:
  pme:
    solvent_model: tip4pew
    nonbonded_method: PME
    nonbonded_cutoff: 9*angstroms
    clearance: 12*angstroms
    positive_ion: Na+
    negative_ion: Cl-

systems:
  protein-ligand:
    phase1_path: [complex.prmtop, complex.inpcrd]
    phase2_path: [ligand.prmtop, ligand.inpcrd]
    ligand_dsl: resname LIG
    solvent: pme

protocols:
  absolute-binding:
    complex:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00]
        lambda_restraints:     [0.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00]
    solvent:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00]

experiments:
  system: protein-ligand
  protocol: absolute-binding
  restraint:
    type: Harmonic

```
