### ISSUE TITLE
Yank Binding affinity discrepancy between Yank 0.23.4 and Yank 0.20.1

### ISSUE THREAD

**Issue by nividic** [choderalab/yank#1089]
Hi There, 

I was trying to calculate the binding affinity of Lysozyme bonded to Toluene. I was performing the calculation by using Yank 0.23.4. Unfortunately, the produced result is quite off compared the experimental value: Exp = ~ -5 kcal/mol vs Yank_0.23.4 = ~ -11 kcal/mol. I decided to run the same calculation by using the Yank version 0.20.1 which should be the last version before the sampling engine redesign and I’ve got a closer result Yank_0.20.1 = ~ -3.9 kcal/mol. Looking at the Yank reports, it is clear where this difference is probably coming from:

Yank 0.23.4

Free energy of binding  :   -18.524 +- 0.604 kT (-11.043 +- 0.360 kcal/mol)
DeltaG complex          :    26.034 +- 0.580 kT
DeltaG standard state correction:             -3.241 kT
DeltaG solvent          :     4.269 +- 0.169 kT
Enthalpy of binding     :    30.463 +- 1519.819 kT (18.161 +- 906.058 kcal/mol)   

Yank 0.20.1 

Free energy of binding  :    -6.623 +- 0.205 kT (-3.948 +- 0.122 kcal/mol)
DeltaG complex          :    25.620 +- 0.128 kT
DeltaG standard state correction:            -14.602 kT
DeltaG solvent          :     4.395 +- 0.160 kT
Enthalpy of binding     :    13.298 +- 18.044 kT (7.927 +- 10.757 kcal/mol)

The DeltaG standard state corrections are quite different while the two alchemically decoupling simulations are providing close energies. I have attached a link to a file with the runs for the two Yank versions tested (I’m sorry it is a quite large file).

Can you please look at the results and try to see where this issue is coming from? Thank you so much.

https://drive.google.com/file/d/1WGX1xtz_SnZLJXLaCKeuf3FgeW7xBiWb/view?usp=sharing

**Comment by jchodera** [comment]
In [release 0.22.0](https://github.com/choderalab/yank/releases/tag/0.22.0), @Lnaden changed the way we compute the standard state correction, so it's possible something unexpected was introduced and not caught by the unit tests.

However, my guess is that it's the way we pick Boresch restraints. Here's the YAML you included for 0.23.4:
```yaml
options:
  resume_setup: no
  resume_simulation: no
  setup_dir: setup
  experiments_dir: experiments
  verbose: yes
  minimize: yes 
  default_number_of_iterations: 1000 
  temperature: 300*kelvin
  pressure: 1*atmosphere
  output_dir: boresch

molecules:
  T4:
    filepath: input/4w53_apo_pmd_oe.pdb
  itoluene:
    filepath: input/toluene_oe.mol2
    antechamber:
      charge_method: bcc

common_PME: &common_PME
  nonbonded_method: PME
  clearance: 12*angstroms
  nonbonded_cutoff: 11*angstroms
  switch_distance: 10*angstroms
  ewald_error_tolerance: 1.0e-4
  positive_ion: Na+
  negative_ion: Cl-
  ionic_strength: 50*millimolar

solvents:
  pme:
    <<: *common_PME
    solvent_model: tip3p
    leap:
      parameters: [leaprc.protein.ff14SB, leaprc.water.tip3p]

systems:
  explicit:
    receptor: T4
    ligand: itoluene
    solvent: pme
    leap:
      parameters: [leaprc.protein.ff14SB, leaprc.gaff2, leaprc.water.tip3p]

protocols:
  absolute-binding:
    complex:
      alchemical_path:
        lambda_electrostatics: [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.90, 0.78, 0.64, 0.51, 0.35, 0.20, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.80, 0.70, 0.60, 0.50, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00]
        lambda_restraints:     [0.00, 0.025, 0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.75, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00]
    solvent:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.90, 0.78, 0.64, 0.51, 0.35, 0.20, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.80, 0.70, 0.60, 0.50, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00]

experiments:
  system: explicit
  protocol: absolute-binding
  restraint:
    type: Boresch
```
First, if you use Boresch restraints with T4 lysozyme, you also have to use the painful [confine-and-release method](http://www.choderalab.org/publications/2014/4/26/confine-and-release-method-obtaining-correct-binding-free-energies-in-the-presence-of-protein-conformational-change?rq=confine), which you'd have to code up your own solution before. We don't recommend that for problems like this. Instead, you should be using `Harmonic` or `FlatBottom` since it allows the ligand to rotate freely.

With Boresch-style restraints, YANK will choose a different set of atoms to restraint each time you run it. If you run multiple instances, you might end up sampling totally different poses, and if the unrestraint replica doesn't sample all the conformations, you will see very different binding affinities. 

I haven't yet had a chance to examine all the replicas and whether they sample *all* possible toluene orientations, but I'd just repeat the calculation with `Harmonic` and see what happens.

There are also lots of other things we should update in your YAML file for 0.23.4. @andrrizzi: Can you help out @nividic with this?
