### ISSUE TITLE
Implement automatic setup of replicate calculations

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#1179]
I'm thinking of adding a `replicate` option in the YAML interface that will instruct the experiment builder to run multiple runs. It would look like something like this
```yaml
experiments:
  system: t4-toluene
  protocol: binding
  sampler: repex
  options:
    temperature: 298.15*kelvin
  replicates: 5
```
This would also allow us to perform replicate-informed analysis once the calculation is over.
