### ISSUE TITLE
Possible issue with net_charge assignment from yaml with antechamber

### ISSUE THREAD

**Issue by mjw99** [choderalab/yank#1220]
Is [this](https://github.com/choderalab/yank/blob/9496213f20dd790d92e7ea183fa9c23ab4551802/Yank/pipeline.py#L1685) correct? It would suggest net_charge read in from:
```
molecules:
  fragment:
    filepath: fragment10.mol2
    antechamber:
      charge_method: bcc
      net_charge: 1
```

would never be assigned?
