### ISSUE TITLE
Hydration free energy protocol does not turn off steric interaction in vacuum

### ISSUE THREAD

**Issue by isjoung** [choderalab/yank#1236]
Hi,
I am curious why ``auto`` ``alchemical_path`` does not turn off steric interaction in vacuum.
This is the result yaml file stored in the 'experiments' directory.

```yaml
---
version: '1.3'
options:
    anisotropic_dispersion_cutoff: auto
    default_number_of_iterations: 5000
    minimize: true
    output_dir: ..
    pressure: 1*atmosphere
    temperature: 298.15*kelvin
    verbose: true
solvents:
    pme:
        nonbonded_cutoff: 0.9*nanometer
        nonbonded_method: PME
    vacuum:
        nonbonded_method: NoCutoff
systems:
    hydration-system:
        model.inpcrd: ../../model.inpcrd
        model.nosolv.inpcrd: ../../model.nosolv.inpcrd
        model.nosolv.prmtop: ../../model.nosolv.prmtop
        model.prmtop: ../../model.prmtop
        phase1_path: [model.prmtop, model.inpcrd]
        phase2_path: [model.nosolv.prmtop, model.nosolv.inpcrd]
        solvent1: pme
        solvent2: vacuum
protocols:
    hydration-protocol: !Ordered
        solvent1:
            alchemical_path:
                lambda_electrostatics: [1.0, 0.9905524277678165, 0.9714490701961671,
                    0.952213046616656, 0.9339876892075158, 0.9161544433149477, 0.8965700892917489,
                    0.8752188540162116, 0.8542485032123845, 0.8334861754076288, 0.8119572393900822,
                    0.7901947778283928, 0.769417724527257, 0.7484899670959902, 0.7273616101306319,
                    0.7064330005760593, 0.683826694160037, 0.6613802214835333, 0.6403903592796849,
                    0.6198426416968718, 0.5989188322327857, 0.5767918910018383, 0.5543074318616696,
                    0.5323459545669708, 0.5105299397269861, 0.48778874584515924, 0.46450324644689195,
                    0.441927726059105, 0.4186635315960094, 0.39455888617469276, 0.37021635025900307,
                    0.3469894480542111, 0.3250361566483826, 0.30159355221246503, 0.2763846585406633,
                    0.25100948802583545, 0.22604398632962777, 0.2020950055186132,
                    0.1794805990986213, 0.15514159739583683, 0.12967701796237757,
                    0.10432354237587298, 0.07793706258074591, 0.053170344706094184,
                    0.028922248980790113, 0.00488481561881729, 0.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
                lambda_sterics: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                    1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                    1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                    1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9582338384258883,
                    0.9081669120954781, 0.8580042944058157, 0.8133912240612111, 0.7707517244155118,
                    0.7253354968860211, 0.6814628758495077, 0.6404279258903955, 0.6049541898433882,
                    0.5732631248614026, 0.5444971281977355, 0.5168574442299599, 0.4867376081040632,
                    0.45302911729692974, 0.4165223001222631, 0.38101273917355877,
                    0.3489920913196398, 0.31681492671334255, 0.2869348962970577, 0.2588845303540649,
                    0.23176095399858318, 0.20315631773306317, 0.17036285517287994,
                    0.13005787881271624, 0.07729001328548783, 0.0]
            trailblazer_options:
                bidirectional_redistribution: true
                constrain_receptor: false
                distance_tolerance: 0.05
                n_equilibration_iterations: 1000
                n_samples_per_state: 100
                reversed_direction: true
                thermodynamic_distance: 0.5
        solvent2:
            alchemical_path:
                lambda_electrostatics: [1.0, 0.9865546836508414, 0.8637408903992221,
                    0.7314286873692144, 0.5931519119034251, 0.458125723008042, 0.3305900794763034,
                    0.2010854735478622, 0.08966384245185711, 0.0]
                lambda_sterics: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            trailblazer_options:
                bidirectional_redistribution: true
                constrain_receptor: false
                distance_tolerance: 0.05
                n_equilibration_iterations: 1000
                n_samples_per_state: 100
                reversed_direction: true
                thermodynamic_distance: 0.5
experiments:
    protocol: hydration-protocol
    system: hydration-system
```
