### ISSUE TITLE
Error with reading yaml file 

### ISSUE THREAD

**Issue by Byun-jinyoung** [choderalab/yank#1248]
Hi yank users,

I've been trying to calculate absolute binding free energy with YANK. But I encountered the error as below:
```
yaml.scanner.ScannerError: mapping values are not allowed here
  in "T-P23D03.yaml", line 32, column 17
```
Below is my input yaml file:

```
---
options:
  minimize: yes
  verbose: yes
  temperature: 300 * kelvin
  pressure:  1 * atmosphere
  output_dir: double
  precision: double
  platform:  CUDA
  resume_setup: yes
  resume_simulation: yes
  default_timestep:  2.0 * femtoseconds
  default_nsteps_per_iteration: 500
  default_number_of_iterations: 200
  number_of_equilibration_iterations: 100
  equilibration_timestep: 1.0 * femtosecond


molecules:
  Tubulin:
    filepath: INPUT/COMPLEX/Tubuiln_recepotr.pdb
  LIG:
    filepath: INPUT/LIG/lig.mol2
    antechamber:
      charge_method: bcc
  Ca1:
    filepath: INPUT/Ca1_fix.pdb
    leap:
      parameters: [ INPUT/cal.lib, INPUT/frcmod.mca ]
  Ca2:
    filepath: INPUT/Ca2_fix.pdb
      parameters: [ INPUT/cal.lib, INPUT/frcmod.mca ]
  Mg1:
    filepath: INPUT/Mg1_fix.pdb
      parameters: [ INPUT/mag.lib, INPUT/frcmod_mg.mmg ]
  Mg2:
    filepath: INPUT/Mg2_fix.pdb
      parameters: [ INPUT/mag.lib, INPUT/frcmod_mg.mmg ]

solvents:
  pme:
    nonbonded_method: PME
    switch_distance: 11*angstroms
    nonbonded_cutoff: 12*angstroms
    ewald_error_tolerance: 1.0e-4
    clearance: 9*angstroms
    positive_ion: Na+
    negative_ion: Cl-

systems:
  complex:
    receptor: Tubulin
    ligand:   [LIG, Ca1, Ca2, Mg1, Mg2]
    pack: yes
    solvent:  pme
    leap:
      parameters: [leaprc.protein.ff14SB, leaprc.gaff, leaprc.water.tip4pew, leaprc.phosphate, INPUT/cal.lib, INPUT/mag.lib, INPUT/frcmod.mca, IN\
PUT/frcmod_mg.mmg ]

samplers:
  replica-exchange:
    type: ReplicaExchangeSampler
    replica_mixing_scheme: swap-all
    online_analysis_interval: 100
    online_analysis_target_error: 3.0
    online_analysis_minimum_iterations: 50

protocols:
  absolute-binding:
    complex:
      alchemical_path:
        lambda_restraints:     [0.00, 0.05, 0.10, 0.15, 0.20, 0.25, 0.50, 0.75, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00,\
 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, \
1.00, 1.00, 1.00, 1.00, 1.000, 1.00, 1.000, 1.00, 1.00]
        lambda_electrostatics: [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50,\
 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, \
0.00, 0.00, 0.00, 0.00, 0.000, 0.00, 0.000, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00,\
 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, \
0.25, 0.20, 0.15, 0.10, 0.075, 0.05, 0.025, 0.01, 0.00]
    solvent:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10,\
 0.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00,\
 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.00]

experiments:
  system:   complex
  protocol: absolute-binding
  restraint:
    type: Boresch
```
I just followed the examples with my inputs. 
how can I fix this problem? It is whether from yank or from yaml???
