### ISSUE TITLE
ligand position after trailblazing

### ISSUE THREAD

**Issue by isjoung** [choderalab/yank#1255]
Hi,
I have a problem in maintaining the initial ligand position. I use trailblazer to construct the alchemical path but I find that the ligand is drifted away from the initial position.  Also, it seems that the restraint of the ligand is applied on the new position where it is drifted away.

My restraint is like below:
```
  restraint:
    type: FlatBottom
    spring_constant: 5.0 * kilocalories_per_mole/(angstrom**2)
    well_radius: 0.5 * nanometers
```

Even the ligand in the completely decoupled state stays near the position where it is drifted away initially. That's why I believe that the positional restraint is also shifted.

I tried ``n_equilibration_iterations : 0`` but the problem still remains.

This only happens when I use the trailblazer. How can I avoid this issue while using the trailblazer?
