### ISSUE TITLE
Issues about the calculation of solvation free energy in organic solvent 

### ISSUE THREAD

**Issue by Dropletsimuli** [choderalab/yank#1280]
Hi,
I am new to study YANK for the calculation of NaTFSI solvation free energy in 1,2-Dimethoxyethane (DME). So, I designed the system using `.gro` file and `.top` file.
Here is the .yaml file:
```
---
options:
  minimize: yes
  verbose: yes
  output_dir: results
  platform: CUDA
  temperature: 298*kelvin
  pressure: 1*atmosphere
  checkpoint_interval: 50

systems:
  dme-system:
    phase1_path: [natfsi_dme_mix.gro, ./top/natfsi_dme_mix.top]
    phase2_path: [natfsi.gro, ./top/natfsi.top]
    ligand_dsl: resid 1
    solvent_dsl: resname DME
    solvent1: liquid
    solvent2: gas

solvents:
    liquid: 
        nonbonded_method: PME
        nonbonded_cutoff: 10*angstroms
        clearance: 16*angstroms
    gas:
        nonbonded_method: NoCutoff

protocols:
  hydration-protocol:
    solvent1:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]
    solvent2:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]

experiments:
  system: dme-system
  protocol: hydration-protocol
```
`natfsi.gro` contains one NaTFSI molecule. `natfsi_dme_mix.gro` contain one NaTFSI molecule and 6000 DME molecule.

Then I got the results. But it seems wierd for the reason that most solvation free energy is < 0 .
```
Free energy of solvation:    69.346 +- 0.594 kT (41.066 +- 0.352 kcal/mol)
DeltaG solvent1         :    -9.227 +- 0.460 kT
DeltaG standard state correction:              6.437 kT
DeltaG solvent2         :    66.556 +- 0.376 kT
Enthalpy of solvation   :   139.169 +- 98.876 kT (82.414 +- 58.553 kcal/mol)
```
Is the system I designed to calculate the free energy of solvation reasonable? Or should I set a single molecule of NaTFSI as `phase1_path` and mixture as `phase2_path`? Any suggestion or tips would be apperciated.

Best,
Drep.
