### ISSUE TITLE
Add ability to specify pH in YAML file

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#359]
We should add the ability to also specify the `pH` passed to Epik in the YAML file.

Currently, only the default pH of 7.4 is used during the call to [`run_epik`](https://github.com/choderalab/yank/blob/master/Yank/yamlbuild.py#L861-L862).

@andrrizzi: Would you be able to add this sometime this week?

**Comment by andrrizzi** [comment]
Sure! I can handle this on Wednesday.

**Comment by andrrizzi** [comment]
By the way, do we want `tautomerize=True` in the end?

**Comment by jchodera** [comment]
Maybe we can control that with an option?

**Comment by jchodera** [comment]
We can set it to be `False` by default.

**Comment by andrrizzi** [comment]
> Maybe we can control that with an option?

Yeah, I was thinking an option in the `solvent`?

> We can set it to be `False` by default.

Will do.

**Comment by andrrizzi** [comment]
At first I thought I could add the `pH` option in the solvent section, but now I'm thinking that may cause running different molecules without the user realizing it. Also, for how the pipeline is set up, this will take me a lot of time to implement. Instead, I'm thinking add support for a syntax like

```yaml
molecules:

  benzene_default:
    smiles: c1ccccc1
    parameters: antechamber
    epik: 0

  benzene_custom:
    smiles: c1ccccc1
    parameters: antechamber
    epik:
      extract_range: 0
      ph: 7.0
      tautomerize: yes
```
