### ISSUE TITLE
How can we specify additional forcefield loading statements for LEaP?

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#360]
For dealing with divalent cations, we need to do more than load a `leaprc.*` file.

There is an additional step of loading another `frcmod` file:
```
source leaprc.ff14SB 
loadAmberParams frcmod.ionslrcm_hfe_tip3p 
```
Do we currently have the capability to specify these extra lines to be passed to leap?

**Comment by andrrizzi** [comment]
Currently `YamlBuilder` automatically includes `frcmod.ionslrcm_tip3p` when it finds that the user wants ions ([here](https://github.com/choderalab/yank/blob/master/Yank/yamlbuild.py#L618-L620)). I actually didn't know that there was need of yet another one for divalent ions. I'll fix this.

**Comment by jchodera** [comment]
There are a few choices for divalent cations that require adding in different `.frcmod` files.

I wonder if we could have a general block that gets included after `source`ing the `leaprc` file in case extra parameters need to be included (e.g. for other cofactors or ions).

**Comment by andrrizzi** [comment]
Are there other use cases beside the ions for which we may want to add leap snippets? I'm just trying to figure out what's the best way to fit this into the current syntax.

**Comment by jchodera** [comment]
I think it is primarily parameter sets that need to be included. Ions, for
example, or cofactors for which parameters are already available (like ATP).

**Comment by juliebehr** [comment]
Discussed this with @andrrizzi but adding it here for the record!

I have another use case that requires changes to the ```leap.in``` file that is generated.  I have a peptide that includes a phosphorylated residue, and need to use the parameters found in [the Amber param database](http://sites.pharmacy.manchester.ac.uk/bryce/amber/).  I have ```.off``` and ```frcmod``` files.  The ```frcmod``` (since in my case I only have 1 of them, and also don't need a small molecule parameter set because my ligand is a peptide) can be loaded as the parameter file in my ```yaml```, because ```tleap``` can load ```frcmod```s via ```LoadAmberParams```:
```
molecules:
  peptide:
    filepath: peptide.pdb
    parameters: frcmod_S2P
    strip_protons: yes
```

But I need to add 
```
loadOff S2P.off
```
to my ```leap.in``` in order to load the rest of the parameters I need from the ```.off``` file.  Also, if you had a setup with ATP, the parameters come in the form of ```.prep``` and ```frcmod``` and I think you would need to use ```loadAmberPrep``` to load the ```.prep``` files.

**Comment by andrrizzi** [comment]
Thanks! I'll work on this as soon as I spare some time.

**Comment by jchodera** [comment]
I think we could add a section (`leap_lines:` or `leap_extra:` or `leap_prefix:` or something else) that takes a list, like:
```YAML
molecules:
  peptide:
    filepath: peptide.pdb
    parameters: leaprc.ff99SB
    leap_lines:
    - loadAmberParams frcmod_S2P
    - loadOff S2P.off
    strip_protons: yes
```
Note that the `parameters` section is intended to load a `leaprc`, I think, which we still need to do even if we have an `frcmod` file since the base atom types need to be loaded---the frcmod just adds some extras.

**Comment by andrrizzi** [comment]
Currently `parameters` handle both `.frcmod` and `.leaprc` files. This can work because it loads by default the `leaprc.gaff` with small molecules.

If we plan to move away from leap, maybe it's better to expand the syntax to load multiple parameters files (and use the right command based on the extension)? Something like
```yaml
molecules:
  peptide:
    filepath: peptide.pdb
    parameters: {leaprc.ff99SB, frcmod_S2P, S2P.off}
    strip_protons: yes
```

**Comment by jchodera** [comment]
That's a neat idea!  We could either force users to standardize extensions/prefixes, like
```YAML
molecules:
  peptide:
    filepath: peptide.pdb
    parameters: {leaprc.ff99SB, S2P.frcmod, S2P.off}
    strip_protons: yes
```
or we could somehow allow uses to specify what kind of parameters they are providing.

Do we want to have some way for the user to select whether to use the `leap`-based setup pipeline as opposed to a different pipeline?  I wonder if this would make it easier to move to a different setup pipeline in the future, rather than having to autodetect everything.  It could be as simple as requiring the user specify this inside a `leap:` block, though it would make it easier for us to separate general file processing (e.g. stripping protons) from parameterization:
```
molecules:
  peptide:
    filepath: peptide.pdb
    strip_protons: yes
    leap:
       parameters: {leaprc.ff99SB, frcmod_S2P, S2P.off}
```

**Comment by jchodera** [comment]
For @luirink's case, this would be:
```YAML
molecules:
  receptor:
    filepath: receptor.pdb
    strip_protons: no
    leap:
      parameters: {leaprc.ff99SBildn, leaprc.gaff, IC6.frcmod, HEME_IC6.off, CYP_IC6.off}
```
