### ISSUE TITLE
Is there some way to standardize the ligand residue name(s) for automated setup pipeline?

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#368]
Can we add some way to specify the ligand residue name set up through the YAML pipeline?

**Comment by andrrizzi** [comment]
Currently, the YAML pipeline should assign as the ligand residue name the first three uppercase letters of its id in the YAML script. For example,
```yaml
molecules:
  bosutinib:
    filepath: myfile.mol2
    parameters: antechamber
```
gets assigned `BOS`. If this doesn't happen, it's a bug. If we want to specify it manually, that needs to be implemented.

**Comment by jchodera** [comment]
OK!  Would be great to allow an override, like
```YAML
molecules:
  bosutinib:
    filepath: myfile.mol2
    parameters: antechamber
    resname: MOL
```
