### ISSUE TITLE
Add capability to start from prmtop inpcrd in YAML script

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#384]
Continuing the discussion started in #380 .

I think I can easily accomodate in the YAML syntax the possibility of starting from a `prmtop`, `inpcrd` pair. **This would also give us an exit for every possible user case not currently supported by the automatic pipeline**. Something like
```yaml
experiments:
  system:
    complex: 'setup/complex.prmtop' # yank look for inpcrd in the same folder
    solvent: 'setup/solvent.prmtop'
    ligand_dsl: 'resname MOL'
    solvent: RF # we need some info about the solvent to pass to OpenMM
  protocol: absolute-protocol
```
Once this is set, we can let `yank prepare` automatically generate the correct YAML script.

The user could specify both `system` and `components`, for example
```yaml
experiments:
  system:
    complex: 'setup/complex.prmtop'
    solvent: 'setup/solvent.prmtop'
    ligand_dsl: 'resname MOL'
    solvent: RF
  components:
    receptor: abl
    ligand: imatinib
    solvent
  protocol: absolute-protocol
```
would run 2 calculations.

In general, I think we should see the automatic setup as an extra feature, not as something the user has to go through.
