### ISSUE TITLE
Changes to YAML syntax for multiple parameters and start from prmtop files

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#410]
I've thought about how to change the syntax to accomodate both #360 and #384, and I've come to 2 conclusions.

* **We can't use normal lists to represent combinations**, or we won't be able to specify simple lists. I think we should change the syntax to become
```yaml
molecules:
  mol_id:
    filepath: 'ligands.sdf'
    parameters: [leaprc.ff99SB, S2P.frcmod, S2P.off]
    select: !Combinatorial [0, 1, 5]
```
* **We should separate system setup in its own block**.  The final part of the script would become
```yaml
...

systems:
  system_from_files:
    complex_phase: 'my_complex.prmtop'
    solvent_phase: 'my_solvent.prmtop'
    ligand_dsl: 'resname MOL'
    solvent: PME-solvent
  system_automatic_setup:
    receptor: abl
    ligand: !Combinatorial [imatinib, bosutinib]
    solvent: PME-solvent
    pipeline: 'leap' # I'd add this once we have an OpenMM pipeline as well
    extra_tleap_commands:
    - loadAmberParams frcmod_S2P
    - anyOtherCommand

experiments:
  system: !Combinatorial [system_from_files, system_automatic_setup]
  protocol: absolute-binding
```
This also has the advantage that **when we'll split the setup pipline into its own tool, the YAML syntax will remain unchanged**.

How does it look? Better solutions?

**Comment by jchodera** [comment]
I've been thinking about this for a little while now.

My concerns come back to worrying about how we support an OpenMM-based setup pipeline (or other non-OpenMM setup pipelines) in the future.

I actually do like the `!Combinatorial` keyword, since this significantly increases flexibility and explicitly highlights combinations of things that should be combinatorially expanded.

In looking at the division between what goes in `molecules` and `system_automated_setup`, what do you think about moving the `parameters` block into the `system_automatic_setup` block, since we probably won't be able to split up parameter definitions between different sets of molecules anyway if we load things through *either* LEaP or OpenMM.  For example, we can't easily apply AMBER96 to a peptide binding to a protein parameterized with AMBER99SB-ILDN in either LEaP or `simtk.openmm.app.ForceField`, so maybe it's safest if we have the `parameters:` block under `system_automatic_setup:`.  

Are the names `system_from_files:` and `system_automatic_setup:` hardcoded, or can we tweak those names a bit (e.g. to `amber_prmtop_loader:` and `ambertools_leap_pipeline:`)?

**Comment by andrrizzi** [comment]
> I actually do like the `!Combinatorial` keyword

Great! I'll implement that.
> Are the names `system_from_files:` and `system_automatic_setup:` hardcoded

Those are just ids for the system. They can be anything you want.
> what do you think about moving the parameters block into the system_automatic_setup block

I can definitely do that! The problem arises when we want to specify molecule-specific parameter files. Do you have an idea about a possible syntax that can substitute
```yaml
molecules:
  imatinib:
    filepath: imatinib.mol2
    parameters: openeye:bcc-gaff  # or parameters: [S2P.frcmod, S2P.off]
```
? Should the user be able to specify parameters both in `molecules` and `systems`?

**Comment by jchodera** [comment]
> The problem arises when we want to specify molecule-specific parameter files.

I'm trying to wrap my head around whether this should be permissible.

The practical use cases I have in mind are:
* Perform a calculation with a *single* parameter set for a combination of ligands and receptors.
* Perform a calculation with *multiple* parameter sets for one ligand and receptor.
* Perform a calculation with *multiple parameter sets for a combination of ligands and receptors.

What I *can't* envisions, however, is using a single YAML file to perform a bunch of calculations on *different* ligand/receptor combinations where each ligand uses a *different* forcefield.  That just doesn't make much sense, since you can't compare anything.  I don't think we need to worry about supporting this case.

Does this make sense?

**Comment by andrrizzi** [comment]
It makes perfect sense, but when you have `imatinib` and `bosutinib` that need a ` imatinib.frcmod` and `bosutinib.frcmod` file to be loaded in tleap respectively, how do you propose to create a combinatorial system if you can specify the parameters only at the system level? Can you write down a proposed syntax? The only solution I see in this case is to specify two sequential systems rather than a single combinatorial one.

Also, the fact that the syntax allows to specify parameters in molecules doesn't mean that we have to support mixing different forcefields. It would just be syntactic sugar to allow combinatorial experiments. We can just let LEaP/OpenMM raise an exception and tell the user to change the script if they do something illegal.

**Comment by jchodera** [comment]
> It makes perfect sense, but when you have imatinib and bosutinib that need a imatinib.frcmod and bosutinib.frcmod file to be loaded in tleap respectively, how do you propose to create a combinatorial system if you can specify the parameters only at the system level?

I see the issue now!  At what stage is the `frcmod` generated? Are you imagining the user has already pregenerated them, or that the pipeline generates them automatically? If we're generating them automatically, can the `pipeline` section handle how it's supposed to do this, and just add the parameters to the listed `extra_tleap_commands` and extra parameters that are specified when generating the real system?

**Comment by andrrizzi** [comment]
> Are you imagining the user has already pregenerated them, or that the pipeline generates them automatically?

My idea was to support both in case the pipeline doesn't do exactly what the user want, so that we won't have to tweak our automatic pipeline every time a user wants something different.

Even with only automatic generation though I see, issues. A concrete example:
```yaml
systems:
  my_system_id:
    receptor: abl
    ligand: !Combinatorial [imatinib, bosutinib]
    parameters: ...
```
What do we put for `parameters`? Do we just assume that some special keywords apply only to `ligand` and put `[leaprc.ff14SB, antechamber]`? Or that `antechamber` and `openeye:bcc-gaff` apply only to non-pdb files?

Even with `extra_tleap_commands`
```yaml
systems:
  my_system_id:
    receptor: abl
    ligand: !Combinatorial [imatinib, bosutinib]
    parameters: leaprc.ff14SB
    pipeline: 'leap'
    extra_tleap_commands:
    - loadAmberParams ...
```
What do we put for `loadAmberParams`? Do we just write `molecule.frcmod` and implement the code to infer the correct path to the file generated by `antechamber`?

IMO, the cleanest and clearest syntax, is to allow the user to specify `parameters` in the `molecules` section as well. Maybe limit parameters specification in `molecules` to special keywords only?

**Comment by jchodera** [comment]
Good points!

This is just random brainstorming, but if I had to come up with something flexible, I'd say
```yaml
systems:
  my_system_id:
    receptor: abl
    ligand: !Combinatorial [imatinib, bosutinib]
    pipeline: 'leap' # select the LEaP setup pipeline
    pipeline_options: # options that are passed to the pipeline
      leaprc: leaprc.ff14SB # select which .leaprc file to include
      leap_include: | # the next few lines are included as a block in the LEaP input file
        # include ATP parameters for cofactor
        loadAmberParams ATP.frcmod
      antechamber: # these options are passed to 'antechamber' when setting up ligands
        chargemethod: bcc  # argument to antechamber
```

**Comment by andrrizzi** [comment]
That's very nice, but the problem remains: we have to tell YamlBuilder which molecules to parametrize with antechamber and which don't. We can't simply parametrize automatically only `ligand`s molecules because it means we won't be able to run benzene-toluene systems, for example. Parametrize all non-pdb files?

I'm still worried about not being able to specify user-defined parameters file, although I honestly don't know how many people will want to try out a different (or their own) parametrization schemes. You surely have a better overall vision on this issue.

**Comment by jchodera** [comment]
Ah, I get it now: We need some way to determine whether we should preprocess the molecules through a parameterization pipeline, and if so, which pipeline to process them through. For example, small molecules may need to be processed through `antechamber`, possibly also adding charges with `openeye` tools. Some small molecules may even be specified via PDB files, so we can't simply autodetect file format.

This is again daydreaming, I wonder if there's a way to generalize this a bit to specify which pipeline we should process things through on a per molecule-set basis, rather than adding a number of specialized attributes to the individual molecules sections. Something like this might allow us to keep the exposed processing pipeline explicitly represented in the YAML file while keeping the parameters for each tool locally grouped under that tool's name in the pipeline definition:
```YAML
molecules:
  small_molecule_ligands:
    filepath: 'ligands.sdf'
    pipeline: small_molecule_pipeline
    select: !Combinatorial [0, 1, 5]
  host:
    filepath: 'host.pdb'
    pipeline: supramolecular_host_pipeline
  receptor:
    filepath: 'kinase.pdb'
    pipeline: protein_pipeline

pipelines:
  small_molecule_pipeline:
    epik:
    - pH: 7.4
    - protonate: yes
    - tautomers: no
    - select: !Combinatorial [0, 1, 2]
    openeye:
    - oequacpac
    antechamber:
    - bondtype: 1
    leap: # these are cached for inclusion in the final leap setup stage
    - parameters: leaprc.gaff

  protein_pipeline:
    pdbfixer:
    - add_missing_heavyatoms: yes
    leap:
    - parameters: [leaprc.ff99SB, S2P.frcmod, S2P.off]
    - include: | # these are cached for inclusion in the final leap setup stage
      extra_include_lines
```
This is actually very similar to what you have now, but with some generalization of the pipeline (rather than specific options for `antechamber:am1bcc` or `openeye:am1bcc`).

**Comment by andrrizzi** [comment]
This looks amazing! I agree that the specification of the pipeline should go along that direction (although I would postpone some of those features after yank 1.0).

The only thing is that **I would avoid having a `pipelines` section**. The `molecules` section is already a "molecule-specific pipeline" and I'd like to keep the syntax as flat as possible. If there are big common portions of the pipeline, **these are already perfectly legal scripts**:
```yaml
molecules:
  small_molecule:
    filepath: !Combinatorial [mol1.mol2, mol2.mol2]
    epik:
      pH: 7.4
      protonate: yes
      tautomers: no
      extract_id: !Combinatorial [0, 1, 2]
    parameters: antechamber
```
or equivalently
```yaml
common_pipeline: &common
  epik:
    pH: 7.4
    protonate: yes
    tautomers: no
    extract_id: !Combinatorial [0, 1, 2]
  parameters: antechamber

molecules:
  small_molecule1:
    filepath: mol1.mol2
    <<: *common
  small_molecule2:
    filepath: mol2.mol2
    <<: *common
```

**Comment by jchodera** [comment]
> The molecules section is already a "molecule-specific pipeline" and I'd like to keep the syntax as flat as possible.

Ah!  Excellent point!

**Comment by jchodera** [comment]
> I agree that the specification of the pipeline should go along that direction (although I would postpone some of those features after yank 1.0).

I am certainly onboard with that. The only thing to make sure of right now is that we have a concept of how it will be extensible without writing ourselves into a corner.

**Comment by andrrizzi** [comment]
Ok, I think this is the only big change to the YAML syntax before releasing 1.0, so I'd like to get this done before setting up all examples and validation scripts.

Here's a summary **proposal for YANK 1.0**
```yaml
molecules:
  my-small-molecule:
    filepath: imatinib.mol2
    openeye:
      quacpac: am1-bcc  # this will be the only supported OpenEye step in yank 1.0
    antechamber:
      charge_method: rc  # this can be any charge scheme supported by antechamber, and it
                         # will be the only antechamber option supported by yank 1.0
    epik:
      ph: 7.4
      tautomerize: yes
      select: 2
      # and any other keyword argument in openmoltools.schrodinger.run_epik() (already implemented)

    leap:
      parameters: [leaprc.gaff, imatinib.frcmod, imatinib.off]
      # Parameter files DO NOT HAVE to be specified if the molecule goes through 
      # antechamber as the correct files will be automatically detected.

      # I WOULD NOT include the feature to include extra tleap commands here because
      # adding support for any command is hard. The user can still set up its own tleap
      # script (modifying the one automatically generated) and create a system starting
      # directly from prmtop and inpcrd files
```
if you agree @jchodera, I can start implementing the changes.
