### ISSUE TITLE
Sign flipped for hydration free energies?

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#446]
I'm looking at some test data from the `hydration-smiles` example, and the `analysis.yaml` file contains:
```YAML
- [solvent1, 1]
- [solvent2, -1]
```
If the alchemical states are defined such that state 0 is fully-interacting:
```YAML
protocols:
  hydration-protocol:
    solvent1:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]
    solvent2:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]
```
and we have `solvent1` is water:
```YAML
systems:
  hydration-system:
    solute: molecule
    solvent1: water
    solvent2: vacuum
```
then I think we have the signs flipped from standard convention, which usually reports the vacuum-to-water transfer free energy (where a negative free energy indicates the molecule prefers water).

I think the easiest thing to do is just to reverse the order of `water` and `vacuum` in the `systems:` block.
