### ISSUE TITLE
Add YAML Options to pass to the generalized restraint code

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank#507]
Follow up to #348

**Comment by andrrizzi** [comment]
Now that I have a better idea of how the API will look ( #535 ), I'm thinking to move the specification of the restraint type from the `options` to the `systems` section.
```yaml
systems:
  Abl-imatinib:
    receptor: Abl
    ligand: imatinib
    solvent: PME
    restraint: Boresch # This means Boresch restraint with default parameters
```
when the API to pass pass parameters manually will be in (post pre-release), the syntax will be expanded to
```yaml
molecules:
  imatinib:
    filepath: input/imatinib.mol2
    ...
    restrained_atoms_dsl: index 2 to 3  # The specification of the restraints atoms must be molecule-based
  Abl:
    filepath: input/2HYY-pdbfixer.pdb
    binding_site_dsl: resid 10 to 35  # We'll be able to add both "binding_site" or "restrained_atoms" here

systems:
  Abl-imatinib:
    ...
    restraint:  # we would still be able to specify "Boresch" here to get all default parameters
      type: Boresch
      K_thetaA: 15.0 * unit.kilocalories_per_mole / unit.radian**2
      K_thetaB: 15.0 * unit.kilocalories_per_mole / unit.radian**2
      # all other parameters are taken to be default value
```
**Question**: Do you think we should *not* allow the syntax
```yaml
systems:
   Abl-imatinib:
    ...
    restraint: Boresch
```
when all parameters are taken as default? Anything else you think I should change?

**Comment by Lnaden** [comment]
I think this is what you are working on for #545, yes?

**Comment by andrrizzi** [comment]
Yep!

**Comment by andrrizzi** [comment]
I'm actually thinking about moving the `restraint` specification in the `experiments` section because the section `systems` should only contains arguments that are passed to the pipeline, but the restraint should be controlled by `Yank`. Any objection?
```yaml
molecules:
  ...
  Abl:
    filepath: input/2HYY-pdbfixer.pdb
    binding_site_dsl: resid 10 to 35

experiments:
  system: !Combinatorial [abl-imatinib, src-imatinib]
  protocol: absolute-binding
  restraint:
    type: Boresch
    K_thetaA: 15.0 * unit.kilocalories_per_mole / unit.radian**2
    K_thetaB: 15.0 * unit.kilocalories_per_mole / unit.radian**2
  options:
    more_options: ...
```
