### ISSUE TITLE
Using our own frcmod file (how avoid antechamber) and/or skip building step (CHARMM support)

### ISSUE THREAD

**Issue by GerardBCN** [choderalab/yank#575]
Hi, 

first of all congratulations for this software, looks really promising.

I'm interested in calculating solvation free energies for a small-molecule forcefield comparison using amber and charmm. My doubts are the following:

a)  In the hydration-phenol-explicit.rst protocol, is there any way to skip the antechamber parameter assignment and provide our own frcmod file?

b) In case I wanted to use CHARMM (which is supported by openMM) is there any way to skip the antechamber/building steps (which I can do myself) and jump in the simulation production and analysis with Charmm parameters?

Thanks for your answers

**Comment by Lnaden** [comment]
Thanks for the complement!

> In the hydration-phenol-explicit.rst protocol, is there any way to skip the antechamber parameter assignment and provide our own frcmod file?

Yes! If you have already parameterized your molecule, you should just be able to replace the `antechamber: charge_method` lines with the following lines under your named molecule's header:
```yaml
leap:
   parameters: {YourFile}.frcmod
```
where you replace `{YourFile}` with the path to your frcmod file relative to the yaml script. You will still need to provide the same argument in the `systems` heading so LEaP knows where to get the water and possible ion parameters from. If you are using the examples that are currently [live on the website](http://getyank.org/latest/examples/hydration-phenol-explicit.html), there are examples of how to do that.

>  In case I wanted to use CHARMM (which is supported by openMM) is there any way to skip the antechamber/building steps (which I can do myself) and jump in the simulation production and analysis with Charmm parameters?

At this point, YANK does not have direct CHARMM support, even if you have your own files. We only support AMBER and GROMACS input type files. One of our goals post our 1.0 release is to move away from depending on LEaP and antechamber and move to the OpenMM XML FF format for our input files, and also try to generalize the input pipeline to better support other formats. If you have a way to convert the CHARMM files into one of the other file formats, YANK should be able to read those in and work with those.

Feel free to let me know if this helps!

**Comment by GerardBCN** [comment]
```
I attach my input.yaml:

options:
  minimize: yes
  verbose: yes
  temperature: 300*kelvin
  pressure: 1*atmosphere

molecules:
  mol:
    filepath: ./input/mol.mol2
    leap:
      parameters: ./input/mol.frcmod

solvents:
  water:
    nonbonded_method: PME
    nonbonded_cutoff: 9*angstroms
    clearance: 16*angstroms
  vacuum:
    nonbonded_method: NoCutoff


systems:
  hydration-system:
    solute: mol
    solvent1: water
    solvent2: vacuum
    leap:
      parameters: [leaprc.gaff, frcmod.ionsjc_tip3p, ./input/mol.frcmod]

protocols:
  hydration-protocol:
    solvent1:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.
00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.
30, 0.20, 0.10, 0.00]
    solvent2:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.
00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.
30, 0.20, 0.10, 0.00]

experiments:
  system: hydration-system
  protocol: hydration-protocol

```

However, I get an error on missing parameters when running tleap, even though I source leaprc.gaff and the frcmod file. Is it that maybe I'm not loading the prepi file on tleap? can it be done within your platform?

```
[...]
Could not find angle parameter: C.ar - C.ar - H
Could not find angle parameter: C.ar - C.ar - C.3
Could not find angle parameter: C.ar - C.ar - H
Could not find angle parameter: C.3 - N.3 - H
Could not find angle parameter: C.3 - N.3 - H
Could not find angle parameter: C.3 - N.3 - H
Could not find angle parameter: C.3 - N.3 - H
Could not find angle parameter: N.3 - C.3 - N.3
Could not find angle parameter: H - N.3 - H
Could not find angle parameter: H - N.3 - H
There are missing parameters.
[...] 
For atom: .R<***** 1>.A<C1 1> Could not find vdW (or other) parameters for type: C.ar
For atom: .R<***** 1>.A<C2 2> Could not find vdW (or other) parameters for type: C.ar
For atom: .R<***** 1>.A<C3 3> Could not find vdW (or other) parameters for type: C.ar
For atom: .R<***** 1>.A<C4 4> Could not find vdW (or other) parameters for type: C.ar
For atom: .R<***** 1>.A<C5 5> Could not find vdW (or other) parameters for type: C.ar
For atom: .R<***** 1>.A<C6 6> Could not find vdW (or other) parameters for type: C.ar
For atom: .R<***** 1>.A<C7 7> Could not find vdW (or other) parameters for type: C.3
For atom: .R<***** 1>.A<N1 8> Could not find vdW (or other) parameters for type: N.3
For atom: .R<***** 1>.A<N2 9> Could not find vdW (or other) parameters for type: N.3
For atom: .R<***** 1>.A<H1 10> Could not find vdW (or other) parameters for type: H
For atom: .R<***** 1>.A<H2 11> Could not find vdW (or other) parameters for type: H
For atom: .R<***** 1>.A<H3 12> Could not find vdW (or other) parameters for type: H
For atom: .R<***** 1>.A<H4 13> Could not find vdW (or other) parameters for type: H
For atom: .R<***** 1>.A<H5 14> Could not find vdW (or other) parameters for type: H
For atom: .R<***** 1>.A<H6 15> Could not find vdW (or other) parameters for type: H
For atom: .R<***** 1>.A<H7 16> Could not find vdW (or other) parameters for type: H
For atom: .R<***** 1>.A<H8 17> Could not find vdW (or other) parameters for type: H
For atom: .R<***** 1>.A<H9 18> Could not find vdW (or other) parameters for type: H
```

Thanks for your help. Let me know if you need the input files for further information.
