### ISSUE TITLE
Add support for two solvents when starting from system files

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#578]
Currently it's only possible to specify a single `solvent` in the `systems` section when starting from AMBER or GROMACS files (we don't need to specify the `solvent` with OpenMM XML files since the solvent options are already in it). We should add support for something like
```yaml
systems:
  my_system:
    phase1_path: [solvent.inpcrd, solvent.prmtop]
    phase2_path: [vacuum.inpcrd, vacuum.prmtop]
    ligand_dsl: resname MOL
    solvent1: PME
    solvent2: vacuum
```
I'll open a PR for this soon.
