### ISSUE TITLE
Molecule naming issue

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#593]
It looks like LEaP has some problems with molecule names that involve letters and numbers:
```
> # Load molecules
> AZ13113123 = loadMol2 moli1.mol2
Loading Mol2 file: ./moli1.mol2
Reading MOLECULE named AZ
> 
> # Solvate systems
> addIons2 AZ13113123 Na+ 0
addIons: Argument #2 is type String must be of type: [unit]

    addIons unit ion1 #ion1 [ion2 #ion2]
      UNIT                      _unit_
      UNIT                      _ion1_
      NUMBER                    _#ion1_
      UNIT                      _ion2_
      NUMBER                    _#ion2_

```

**Comment by jchodera** [comment]
Appending more letters to the end doesn't seem to help:
```
> # Load molecules
> AZ13113123MOL = loadMol2 moli1.mol2
Loading Mol2 file: ./moli1.mol2
Reading MOLECULE named AZM
> 
> # Solvate systems
> addIons2 AZ13113123MOL Na+ 0
addIons: Argument #2 is type String must be of type: [unit]

    addIons unit ion1 #ion1 [ion2 #ion2]
      UNIT                      _unit_
      UNIT                      _ion1_
      NUMBER                    _#ion1_
      UNIT                      _ion2_
      NUMBER                    _#ion2_
```
Can we just change the name of the molecule to something like `MOL` internally to the LEaP script?

**Comment by jchodera** [comment]
This seems to actually just be totally broken. Changing the molecule block to 
```
molecules:                                                                                                                                                                                                                                                                                                                                                                
  #AZ13250285:                                                                                                                                                                                                                                                                                                                                                            
  molecule1:                                                                                                                                                                                                                                                                                                                                                              
    smiles: "CC(=O)Nc1cc(ccc1N(C)CCN)Nc2cc(n3c(n2)c(cn3)C#N)NC4CC4"                                                                                                                                                                                                                                                                                                       
    epik:                                                                                                                                                                                                                                                                                                                                                                 
      select: 0                                                                                                                                                                                                                                                                                                                                                           
      ph: 7.4                                                                                                                                                                                                                                                                                                                                                             
      ph_tolerance: 7.0                                                                                                                                                                                                                                                                                                                                                   
      tautomerize: no                                                                                                                                                                                                                                                                                                                                                     
    openeye:                                                                                                                                                                                                                                                                                                                                                              
      quacpac: am1-bcc                                                                                                                                                                                                                                                                                                                                                    
    antechamber:                                                                                                                                                                                                                                                                                                                                                          
      charge_method: null                                                                                                                                                                                                                                                                                                                                                 
```
gives me:
```
> # Load molecules
> molecule1 = loadMol2 moli1.mol2
Loading Mol2 file: ./moli1.mol2
Reading MOLECULE named MOL
> 
> # Solvate systems
> addIons2 molecule1 Na+ 0
addIons: Argument #2 is type String must be of type: [unit]

    addIons unit ion1 #ion1 [ion2 #ion2]
      UNIT                      _unit_
      UNIT                      _ion1_
      NUMBER                    _#ion1_
      UNIT                      _ion2_
      NUMBER                    _#ion2_
```
Do we have some SMILES tests in travis? I wonder how they are passing...

**Comment by Lnaden** [comment]
It says argument 2 is bad, which is the Na+, are you loading in ions?

**Comment by jchodera** [comment]
Oh! Yes, I had the ions in the parameters block (copied from the abl-imatinib example). Will scrutinize the leap log to make sure they are being loaded.

**Comment by jchodera** [comment]
Hm, I have 
```YAML
systems:
  complex:
    receptor: CK2
    #ligand: !Combinatorial [AZ13250285MOL, AZ13113123MOL, AZ13259517MOL, AZ13511057MOL]
    ligand: !Combinatorial [molecule1, molecule2, molecule3, molecule4]
    solvent: !Combinatorial [GBSA, pme]
    leap:
      parameters: [leaprc.protein.ff14SB, leaprc.gaff, frcmod.ionsjc_tip3p]
```
and I have verified that `frcmod.ionsjc_tip3p` defines `Na+`.

Here's the complete `yank.yaml`:
```YAML
---
options:
  minimize: yes
  verbose: yes
  output_dir: .
  number_of_iterations: 100
  nsteps_per_iteration: 500
  temperature: 300*kelvin
  pressure: 1*atmosphere
  timestep: 2.0*femtoseconds
  output_dir: output
  resume_setup: yes
  resume_simulation: yes
  platform: OpenCL

molecules:
  #AZ13250285:
  molecule1:
    smiles: "CC(=O)Nc1cc(ccc1N(C)CCN)Nc2cc(n3c(n2)c(cn3)C#N)NC4CC4"
    epik:
      select: 0
      ph: 7.4
      ph_tolerance: 7.0
      tautomerize: no
    openeye:
      quacpac: am1-bcc
    antechamber:
      charge_method: null
  #AZ13113123:
  molecule2:
    smiles: "Cc1ccc(cc1NC(=O)C)Nc2cc(n3c(n2)c(cn3)C#N)NC4CC4"
    epik:
      select: 0
      ph: 7.4
      ph_tolerance: 7.0
      tautomerize: no
    openeye:
      quacpac: am1-bcc
    antechamber:
      charge_method: null
  #AZ13259517:
  molecule3:
    smiles: "c1cc(cc(c1)Cl)Nc2c3ccncc3c4ccc(cc4n2)C(=O)O"
    epik:
      select: 0
      ph: 7.4
      ph_tolerance: 7.0
      tautomerize: no
    openeye:
      quacpac: am1-bcc
    antechamber:
      charge_method: null
  #AZ13511057:
  molecule4:
    smiles: "c1cc(=O)[nH]cc1c2c(n(nn2)CCN3CCCCC3)c4cc(n5c(n4)c(cn5)C#N)NC6CC6"
    epik:
      select: 0
      ph: 7.4
      ph_tolerance: 7.0
      tautomerize: no
    openeye:
      quacpac: am1-bcc
    antechamber:
      charge_method: null

  CK2:
    filepath: input/protein.pdb
    strip_protons: True

solvents:
  GBSA:
    nonbonded_method: NoCutoff
    implicit_solvent: OBC2

  pme:
    nonbonded_method: PME
    switch_distance: 11*angstroms
    nonbonded_cutoff: 12*angstroms
    ewald_error_tolerance: 1.0e-4
    clearance: 9*angstroms
    positive_ion: Na+
    negative_ion: Cl-

systems:
  complex:
    receptor: CK2
    #ligand: !Combinatorial [AZ13250285MOL, AZ13113123MOL, AZ13259517MOL, AZ13511057MOL]
    ligand: !Combinatorial [molecule1, molecule2, molecule3, molecule4]
    solvent: !Combinatorial [GBSA, pme]
    leap:
      parameters: [leaprc.protein.ff14SB, leaprc.gaff, frcmod.ionsjc_tip3p]

protocols:
  absolute-binding:
    complex:
      alchemical_path:
        lambda_restraints:     [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.000, 1.00, 1.000, 1.00, 1.00]
        lambda_electrostatics: [1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.000, 0.00, 0.000, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.075, 0.05, 0.025, 0.01, 0.00]
    solvent:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.00]
                
experiments:
  system: complex
  protocol: absolute-binding
  restraint:
    type: Harmonic
```
