### ISSUE TITLE
Errors thrown when recognizing GROMACS files for input

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/yank#613]
I'm doing some tests using yank for solvation free energies, in this case for solvation of methanol in cyclohexane, and have run into an issue where it's not recognizing some of my GROMACS input files. Specifically, I get an error:

```yank.yamlbuild.YamlParseError: System smarty-system: _system_files(['methanol.gro', 'methanol.top']) raised RuntimeError('Wrong system files type.',)```

This seems to be raised (at least by looking at the code) when the file extensions don't match `.gro` and `.top`, though in this case they do, so I'm very puzzled.

I'm attaching a tarball. 

[dl.tar.gz](https://github.com/choderalab/yank/files/671301/dl.tar.gz)

**Comment by jchodera** [comment]
We should definitely have Yank print an error message [here](https://github.com/choderalab/yank/blob/master/Yank/yamlbuild.py#L1765-L1766) describing what file types are expected. 

From glancing at the code, it looks like the `type` argument to `_system_files(type)` may be incorrect, but I don't know where that is set. I seem to hazily recall that YANK will actually try a bunch of schemas on your input to see if one succeeds, but I'm not sure if that's actually what happens. I'll give it a try.

**Comment by jchodera** [comment]
In #614, I added code to print out more debug information.

So far, I've just added more debug information, but the failure is puzzling:
```
[LSKI1497:yank-examples/examples/gromacs] choderaj% yank script --yaml gaff.yaml
2016-12-23 14:21:09,182: MPI disabled.
2016-12-23 14:21:09,185: ERROR - yank.yamlbuild - System smarty-system: _system_files(['methanol_cyclohexane_1_300.gro', 'methanol_cyclohexane_1_300.top']) raised RuntimeError("Wrong system file types provided.\nExtensions provided: ['gro', 'top']\nExpected extensions: ['pdb', 'xml']\n",)
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/bin//yank", line 9, in <module>
    load_entry_point('yank==0.15.0.dev0', 'console_scripts', 'yank')()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/yank/cli.py", line 74, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/yank/commands/script.py", line 58, in dispatch
    yaml_builder = YamlBuilder(yaml_source=yaml_path)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/yank/yamlbuild.py", line 1208, in __init__
    self.parse(yaml_source)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/yank/yamlbuild.py", line 1279, in parse
    self._db.systems = self._validate_systems(yaml_content.get('systems', {}))
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/yank/yamlbuild.py", line 1819, in _validate_systems
    raise YamlParseError('System {}: {}'.format(system_id, e.autos[-1]))
yank.yamlbuild.YamlParseError: System smarty-system: _system_files(['methanol_cyclohexane_1_300.gro', 'methanol_cyclohexane_1_300.top']) raised RuntimeError("Wrong system file types provided.\nExtensions provided: ['gro', 'top']\nExpected extensions: ['pdb', 'xml']\n",)
```
I suspect what is happening is that the logic tries to run through every available schema to see if one works, and if none of them work, only the *final* failure error message is provided.

I think this is both an advantage and disadvantage of the scheme @andrrizzi is using. There is likely something wrong with the input files or paths, but we can't tell what it is because we are just trying to interpret them as every possible valid combination of input, each of which fails for a different reason.

The simplest approach to fixing this is probably just to require the user specify an input schema, like `filetype: gromacs`, that would allow us to test just the appropriate input schema and report useful error messages when there is something wrong with the input file.

**Comment by davidlmobley** [comment]
OK. I would note that the files (or at least, the solution-phase ones) work in GROMACS. I haven't tested the gas-phase ones because my current protocol uses decoupling in the solution phase and hence a gas phase calculation is unnecessary. So if there's something wrong with the files, it would be very helpful to get back information as to what it is.

**Comment by davidlmobley** [comment]
(Though, actually, yours is raising an error with the solution-phase files, which work fine for me in GROMACS.)

**Comment by jchodera** [comment]
I don't think it's necessarily something wrong with the files---just that not all of the information is being processed in the right way in the YANK setup pipeline. Still debugging to see exactly where things break.

**Comment by davidlmobley** [comment]
OK. FWIW, I just tried a completely separate system setup in GROMACS format (some SAMPL5 files) and ran into exactly the same issue.

**Comment by jchodera** [comment]
Oh! You don't have a `solvent:` block under your `smarty-system:` section.

From [this code](https://github.com/choderalab/yank/blob/master/Yank/yamlbuild.py#L1794), it looks like that is required.

I don't know how to give a useful error message in this case. Hopefully @andrrizzi can help, since returning useful feedback when things don't work is essential to not driving users crazy.

The `solvent:` block, contrary to its name, mainly specifies the nonbonded treatment to use in the simulation. You probably want something like:
```YAML
systems:                                                                                                                                                                                                                                                                                                                                                                  
  smarty-system:                                                                                                                                                                                                                                                                                                                                                          
    phase1_path: [methanol_cyclohexane_1_300.gro, methanol_cyclohexane_1_300.top]                                                                                                                                                                                                                                                                                         
    phase2_path: [methanol.gro, methanol.top]                                                                                                                                                                                                                                                                                                                             
    ligand_dsl: resname ZBK                                                                                                                                                                                                                                                                                                                                               
    solvent_dsl: not resname ZBK                                                                                                                                                                                                                                                                                                                                          
    solvent: liquid                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                          
solvents:                                                                                                                                                                                                                                                                                                                                                                 
  liquid:                                                                                                                                                                                                                                                                                                                                                                 
    nonbonded_method: PME                                                                                                                                                                                                                                                                                                                                                 
    nonbonded_cutoff: 9*angstroms                                                                                                                                                                                                                                                                                                                                         
  vacuum:                                                                                                                                                                                                                                                                                                                                                                 
    nonbonded_method: NoCutoff
```
Unfortunately, it looks like the current design doesn't permit different solvent conditions to be specified for each liquid phase. I think I can extend this by adding a new schema that allows you to specify `phase1_solvent:` and `phase2_solvent:` separately.

**Comment by jchodera** [comment]
Note that the additions I provide above fail with this useful error message, correctly pointing out that the residue name `ZBK` appears nowhere in your `gro` or `top` files:
```
[LSKI1497:yank-examples/examples/gromacs] choderaj% yank script --yaml gaff.yaml
2016-12-23 14:45:32,487: MPI disabled.
2016-12-23 14:45:32,489: ERROR - yank.yamlbuild - Explicit solvent liquid does not specify clearance.
Wrong system file types provided.
Extensions provided: ['gro', 'top']
Expected extensions: ['inpcrd', 'prmtop']

Wrong system file types provided.
Extensions provided: ['gro', 'top']
Expected extensions: ['inpcrd', 'prmtop']

Correctly recognized files ['methanol_cyclohexane_1_300.gro', 'methanol_cyclohexane_1_300.top'] as ['gro', 'top']
Correctly recognized files ['methanol.gro', 'methanol.top'] as ['gro', 'top']
2016-12-23 14:45:32,504: DSL string for the ligand: "resname ZBK"
2016-12-23 14:45:32,504: Reading phase solvent1
2016-12-23 14:45:33,674: Ligand net charge: 0
2016-12-23 14:45:33,675: Reading phase solvent2
2016-12-23 14:45:33,707: Ligand net charge: 0
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/bin//yank", line 9, in <module>
    load_entry_point('yank==0.15.0.dev0', 'console_scripts', 'yank')()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/yank/cli.py", line 74, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/yank/commands/script.py", line 59, in dispatch
    yaml_builder.build_experiments()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/yank/yamlbuild.py", line 1298, in build_experiments
    self._run_experiment(combination, output_dir)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/yank/yamlbuild.py", line 2461, in _run_experiment
    'the ligand in phase {}.'.format(ligand_dsl, phase.name))
RuntimeError: DSL string "resname ZBK" did not select any atom for the ligand in phase solvent1.
```

**Comment by davidlmobley** [comment]
@jchodera : The solvent block does NOT seem to be required in general. I have an example @andrrizzi gave me which starts simulations from serialized XML files which does not have this, and it runs fine. However, I'm getting results I don't expect, so I was trying to troubleshoot by starting the simulations with an alternate input format to see if it's a problem with Yank, a problem with the serialized XML, or something else. So, this example runs:

```
---
options:
  minimize: yes
  verbose: yes
  number_of_iterations: 1000
  temperature: 300*kelvin
  pressure: 1*atmosphere

systems:
  smarty-system:
    phase1_path: [cyclohexane-SAMPL5_003.pdb, cyclohexane-SAMPL5_003.xml]
    phase2_path: [SAMPL5_003.pdb, cyclohexane-SAMPL5_003_gas.xml]
    ligand_dsl: resname ZJR
    solvent_dsl: not resname ZJR

protocols:
  hydration-protocol:
    solvent1:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]
    solvent2:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00]

experiments:
  system: smarty-system
  protocol: hydration-protocol
```

and I was trying to just modify it to only swap which input files I was using (switching to GROMACS gro and top) without changing anything else. Perhaps that is a mistake.

I'll try and troubleshoot the residue name thing, though when I was starting from serialized XML files and botched the residue name issue, I got a clear error message saying that it didn't find the right residue name, so I wasn't even looking at that here (since I got no such error message).

I'm not sure I follow what you're saying about this:

> Unfortunately, it looks like the current design doesn't permit different solvent conditions to be specified for each liquid phase. I think I can extend this by adding a new schema that allows you to specify phase1_solvent: and phase2_solvent: separately.

Here, I want cyclohexane for one phase and gas for the other. Can that be done from GROMACS format? Presumably, that's why @andrrizzi set me up originally without the `solvent` line (?) since one phase has solvent and the other doesn't.

**Comment by jchodera** [comment]
> @jchodera : The solvent block does NOT seem to be required in general. I have an example @andrrizzi gave me which starts simulations from serialized XML files which does not have this, and it runs fine. 

The serialized System XML file contains critical information like whether you want to use PME, reaction-field, or vacuum simulations, what cutoffs to use, etc.

Where would you expect this information to come from in your `.gro` and `.top` files? Can you point out where that information is stored?

**Comment by davidlmobley** [comment]
To ask that another way -- if I want to run a solvation free energy calculation by providing solvated and gas-phase input files in GROMACS format, what would be the right syntax for doing so?

**Comment by davidlmobley** [comment]
> The serialized System XML file contains critical information like whether you want to use PME, reaction-field, or vacuum simulations, what cutoffs to use, etc.

Ahh, good point, yes.

**Comment by jchodera** [comment]
There's no syntax that supports that right now, but we could create one. I think it would be easiest to use:
```YAML
---
options:
  minimize: yes
  verbose: yes
  number_of_iterations: 1000
  temperature: 300*kelvin
  pressure: 1*atmosphere

systems:
  smarty-system:
    phase1_path: [methanol_cyclohexane_1_300.gro, methanol_cyclohexane_1_300.top]
    phase2_path: [methanol.gro, methanol.top]
    ligand_dsl: resname ZBK
    solvent_dsl: not resname ZBK
    solvent1: liquid
    solvent2: gas

solvents:
  liquid:
    nonbonded_method: PME
    nonbonded_cutoff: 9*angstroms
  gas:
    nonbonded_method: NoCutoff

protocols:
  hydration-protocol:
    solvent1:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]
    solvent2:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00]

experiments:
  system: smarty-system
  protocol: hydration-protocol
```
Does that seem appropriate?
