### ISSUE TITLE
Intermediate states at increased temperature

### ISSUE THREAD

**Issue by daveminh** [choderalab/yank#668]
Can you post suggestions on how to run an intermediate state at a different temperature than the end states?

**Comment by Lnaden** [comment]
Just to double check, you mean to assign higher temperatures to intermediate states, but the end states (and the free energy difference you are computing) will be at the same temperature, correct?

**Comment by daveminh** [comment]
That is correct.

**Comment by andrrizzi** [comment]
I actually think I should be able to integrate this in the YAML interface now that we have the new engine. You'd be able to specify the temperature protocol like normal lambda values
```yaml
protocols:
  binding-protocol:
    complex:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]
        temperature:           [300*kelvin, 305*kelvin, 310*kelvin, 315*kelvin, 320*kelvin, 325*kelvin, 330*kelvin, 335*kelvin, 340*kelvin, 335*kelvin, 330*kelvin, 325*kelvin, 320*kelvin, 315*kelvin, 310*kelvin, 305*kelvin, 300*kelvin, 300*kelvin, 300*kelvin]
    solvent:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]
```
I should have time to add this early next week, if that's early enough for you.
