### ISSUE TITLE
Use infinity instead of None to specify unlimited number of iterations

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#772]
Standard YAML supports infinity indicated as
```yaml
options:
  number_of_iterations: .inf
  online_analysis_target_error: 0.5
```
which get translated into a standard Python object `float('inf')`. What do you think of using that instead of `null`? It will make the internal handling in `Experiment` and `ReplicaExchange` easier too. I noticed a couple of places that may crash in few situations for reasons similar to #771.
