### ISSUE TITLE
modulating torsional barriers as a function of lambda

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/yank#802]
I was thinking to have a short-term rotation student (beginning Nov. 9) look into enhanced sampling of torsional barriers in hydration free energies using Yank, where torsional barriers (e.g. for carboxylic acids) are reduced at intermediate lambda values or as interactions are decoupled. Is this currently feasible with the YAML or API interfaces or would it require a major coding effort? Any suggestions/pointers would be appreciated. 

Ideally/naively, I might like a `torsion_lambda` value or something where I can modulate the barrier of selected torsions. 

The rotation in question is very minimal (about three weeks) so he'd only be able to do it if it's not a major coding effort.

**Comment by andrrizzi** [comment]
Currently, it's possible to soften _all_ torsions of the molecule that is alchemically modulated. It is not possible to modify only specific torsions within the molecule (I think this will require a lot of coding effort).

A couple of months ago, I run a couple of carboxylic acids solvation free energy calculations with softened torsions with the SMIRNOFF force field, but the final free energies were not better. I didn't have time to figure out what the problem was though.

Keep in mind that the torsion softening has not been tested as extensively as the nonbonded part. If you want to give it a shot, just specify your `lambda_torsions` in the protocol together with `labda_electrostatics` and `lambda_sterics`. For example:
```yaml
protocols:
  my-protocol:
    solvent1:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]
        lambda_torsions:       [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]
    solvent2:
      alchemical_path:
        ...
```
