### ISSUE TITLE
Yank tries to use TIP3P/TIP4PEw even if it is not requested if a system block specifies TIP3P

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/yank#811]
Related to #776 and spinning off from the YAML I posted there, I seem to have found a bug where the presence of a `systems` section for tip3p results in Yank trying to use TIP3P/TIP4PEw (and failing due to to #776 ) EVEN IF I AM TRYING TO USE GBSA.

(I'm trying to set up a single YAML file to use in a tutorial, which can work for both implicit or explicit solvent by simply changing a keyword in the `experiments` section. This approach worked some months ago but seems not to anymore.)

Here's the YAML (omitting the options section) which will results in the TIP3P/TIP4PEw failure for me (if I fill in a couple of options):
```
molecules:
  input_molecule:
    filepath: %(output_dir)s/input.mol2
    antechamber:
      charge_method: null

solvents:
  gbsa:
    nonbonded_method: NoCutoff
    implicit_solvent: OBC2
  vacuum:
    nonbonded_method: NoCutoff
  tip3p:
      nonbonded_method: PME
      nonbonded_cutoff: 9*angstroms
      clearance: 8*angstroms
      ewald_error_tolerance: 1.0e-4

systems:
  hydration-gbsa:
    solute: input_molecule
    solvent1: gbsa
    solvent2: vacuum
    leap:
      parameters: [leaprc.gaff, leaprc.protein.ff14SB ]
  hydration-tip3p:
      solute: input_molecule
      solvent1: tip3p
      solvent2: vacuum
      leap:
        parameters: [leaprc.gaff, leaprc.protein.ff14SB, leaprc.water.tip3p]

protocols:
  protocol-gbsa:
    solvent1:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.00]
        lambda_sterics:        [1.00, 0.00]
    solvent2:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.00]
        lambda_sterics:        [1.00, 0.00]

  protocol-tip3p:
    solvent1:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]
    solvent2:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00]

experiments:
  system: hydration-gbsa
  protocol: protocol-gbsa
```

and here's the one which works just fine, which only differs in the `systems` section:
```
molecules:
  input_molecule:
    filepath: %(output_dir)s/input.mol2
    antechamber:
      charge_method: null

solvents:
  gbsa:
    nonbonded_method: NoCutoff
    implicit_solvent: OBC2
  vacuum:
    nonbonded_method: NoCutoff
  tip3p:
      nonbonded_method: PME
      nonbonded_cutoff: 9*angstroms
      clearance: 8*angstroms
      ewald_error_tolerance: 1.0e-4

systems:
  hydration-gbsa:
    solute: input_molecule
    solvent1: gbsa
    solvent2: vacuum
    leap:
      parameters: [leaprc.gaff, leaprc.protein.ff14SB ]


protocols:
  protocol-gbsa:
    solvent1:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.00]
        lambda_sterics:        [1.00, 0.00]
    solvent2:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.00]
        lambda_sterics:        [1.00, 0.00]

  protocol-tip3p:
    solvent1:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]
    solvent2:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00]

experiments:
  system: hydration-gbsa
  protocol: protocol-gbsa
```

**Comment by jchodera** [comment]
Thanks for catching this bug! Assigning @andrrizzi, who built the YAML parser.

What's odd to me is that the [FreeSolv hydration example](https://github.com/choderalab/yank-examples/blob/master/examples/hydration/freesolv/yank.yaml#L19-L25) also specifies both a explicit and implicit solvents in the same file. Wouldn't this have also run afoul of the same issue?

**Comment by davidlmobley** [comment]
Yeah, that's what I haven't been able to figure out. That example runs fine for me. But, it also uses a fairly different way of configuring things, so it's not very easy for me (as a Yank novice) to tell what the important differences are.

**Comment by jchodera** [comment]
Could your indentation be messed up?
```yaml
systems:
  hydration-gbsa:
    solute: input_molecule
    solvent1: gbsa
    solvent2: vacuum
    leap:
      parameters: [leaprc.gaff, leaprc.protein.ff14SB ]
  hydration-tip3p:
      solute: input_molecule
      solvent1: tip3p
      solvent2: vacuum
      leap:
        parameters: [leaprc.gaff, leaprc.protein.ff14SB, leaprc.water.tip3p]
```
The second block is incorrectly indented.

**Comment by jchodera** [comment]
Nope, that's not it. That block parses fine by `yaml.load()`.

**Comment by jchodera** [comment]
OK, I can't figure this out either, and I can confirm the FreeSolv example we had works correctly. 

@davidlmobley : Can you post a zip archive of all the input files needed to reproduce this failure?

**Comment by davidlmobley** [comment]
Quite possibly I've just formatted the YAML wrong or something.
I was playing around with this with the setup_hydration.py and setup_hydration_testing.py scripts in the attached; the most recent is the latter. I can get it to work without the noted block, but with it it fails...

[Archive.zip](https://github.com/choderalab/yank/files/1443744/Archive.zip)

**Comment by jchodera** [comment]
Which script works and which doesn't, and when does it fail?

`setup_hydration_testing.py` ran to completion for me.

In general, it really helps if you can give us a ZIP archive with clear instructions on reproducing the issue you're seeing (and where we should see the failure), rather than fragments of something.

**Comment by jchodera** [comment]
`setup_hydration.py` fails because you've neglected to include a file:
```yaml
[chodera@lilac:mobley]$ python setup_hydration.py 
Traceback (most recent call last):
  File "setup_hydration.py", line 36, in <module>
    shutil.copy(input_molecule, os.path.join(output_dir, 'input.smiles'))
  File "/home/chodera/miniconda/lib/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/chodera/miniconda/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'test.smi'
```
I really do want to fix this, but we need a complete stand-alone test case to even be able to start debugging.

**Comment by davidlmobley** [comment]
Here. As noted above, it fails as is with errors relating to TIP4PEW, but if you remove the following snippet, it will run. Again, I'm probably doing something wrong, but what it is is very unclear, since it seems like this component of the setup should be irrelevant unless the experiments I'm asking for involve explicit solvent.

```
  hydration-tip3p:
    solute: input_molecule
    solvent1: tip3p
    solvent2: vacuum
    leap:
      parameters: [leaprc.gaff, leaprc.protein.ff14SB, leaprc.water.tip3p]
```

[Archive 2.zip](https://github.com/choderalab/yank/files/1443764/Archive.2.zip)

**Comment by jchodera** [comment]
As in #776, you need to add `solvent_model: tip3p` to ensure that the TIP3P water box is used instead of the default TIP4P-Ew box:
http://getyank.org/0.18.0/yamlpages/solvents.html#solvent-model

We'll add this line to the `yank-examples` examples to make this explicit.

**Comment by davidlmobley** [comment]
I understand that if I wanted to run using explicit water, I would need the `solvent_model` specified. The thing that confuses me is that I'm explicitly trying not to use this section: 
```
experiments:
  system: hydration-gbsa
  protocol: protocol-gbsa
```
Why, if I am specifying that it run in gbsa, is it still trying to use the explicit water section? 

I'm guessing what's going on is that the other sections trigger Yank running (or attempting to run) the setup for those portions even if the relevant experiments aren't going to be run, though this is not super obvious to me from the Yaml documentation (or at least I haven't found the section which discusses that). Can you confirm?

Naively it had seemed to me that if I'm not doing an "experiment" with explicit water, Yank should not be setting up the explicit water simulations. (And, that was my goal -- I wanted to distribute a Yaml file which had the code needed for several different types of calculations, but have a script which updates the `experiments' section to select, set up, and run only the one desired at the time. 

Anyway, can you clarify? Is it that all systems/solvents in a file are going to be set up regardless of whether they are listed in the experiments section? If so maybe this should be made more obvious in the Yaml docs.

**Comment by jchodera** [comment]
> I understand that if I wanted to run using explicit water, I would need the solvent_model specified. The thing that confuses me is that I'm explicitly trying not to use this section:

Not quite. `solvent_model` defaults to `tip4pew` when not specified, so you can still use explicit water without specifying `solvent_model`, provided it is TIP4P-Ew.

> Why, if I am specifying that it run in gbsa, is it still trying to use the explicit water section?

I believe @andrrizzi has used the logic that all systems specified in the `systems:` section are set up regardless of which systems you specify you want to carry out experiments on in the `experiments:` section. So if you specify an incompatible set of options in one of the `systems:` entries, it will still cause problems even if you do not use that system.

> Naively it had seemed to me that if I'm not doing an "experiment" with explicit water, Yank should not be setting up the explicit water simulations.

I'm not sure what behavior is best here. On the one hand, I totally agree, but on the other hand, we wouldn't want you to specify a YAML file full of errors but have one part of the YAML file work because you only use a single system from it. We generally want to go with the "principle of least surprisal", where I'd argue that changing from `hydration-gbsa` to `hydration-tip3p` in `experiments` shouldn't suddenly give you errors because the syntax is incorrect. I think we really just need a way to provide much more helpful errors before we dive into optimizing things by pruning setup paths based on experiments that aren't going to be used. 

> (And, that was my goal -- I wanted to distribute a Yaml file which had the code needed for several different types of calculations, but have a script which updates the `experiments' section to select, set up, and run only the one desired at the time.

YANK is first and foremost meant to enable many experiments directed by a single YAML file. I'd set them up to run multiple experiments:
http://getyank.org/0.18.0/yamlpages/experiments.html#running-multiple-experiments

> Anyway, can you clarify? Is it that all systems/solvents in a file are going to be set up regardless of whether they are listed in the experiments section? 

Yes, that seems to be the case.

> If so maybe this should be made more obvious in the Yaml docs.

I totally agree. Created issue https://github.com/choderalab/yank/issues/812

**Comment by davidlmobley** [comment]
Overall that sounds reasonable.

In terms of the mutliple experiments issue -- I was mainly after something like we did on Orion, where one could change the solvent model by changing a single option. In that case, you'd used a single YAML and were only modulating the `experiments` section based on which solvent model was chosen, so I was just trying to reproduce that behavior.

**Comment by jchodera** [comment]
> In terms of the mutliple experiments issue -- I was mainly after something like we did on Orion, where one could change the solvent model by changing a single option. In that case, you'd used a single YAML and were only modulating the experiments section based on which solvent model was chosen, so I was just trying to reproduce that behavior.

This should work provided the input is all formatted correctly and consistently, but it does slow things down a little bit to set up systems you don't need. You might try a more modular approach and swap in only the `system` definitions you're going to use!

**Comment by andrrizzi** [comment]
> I wanted to distribute a Yaml file which had the code needed for several different types of calculations, but have a script which updates the `experiments' section to select

Why not updating the `solvent` section to select the experiment you want to run? This way you won't need to specify multiple systems. Something like:
```yaml
solvents:
  gbsa:
    nonbonded_method: NoCutoff
    implicit_solvent: OBC2
  vacuum:
    nonbonded_method: NoCutoff
  tip3p:
    nonbonded_method: PME
    nonbonded_cutoff: 9*angstroms
    clearance: 8*angstroms
    ewald_error_tolerance: 1.0e-4
    # Notice that you can specify extra parameters file bound to the solvent.
    leap:
      parameters: leaprc.water.tip3p

systems:
  hydration:
    solute: input_molecule
    solvent1: gbsa  # just substitute tip3p here to change solvent.
    solvent2: vacuum
    leap:
      parameters: [leaprc.gaff, leaprc.protein.ff14SB ]
```

Having YANK built all the systems specified helps a lot when we use only the automatic pipeline part (which happened to me quite often recently). I guess we could implement a flag to control this behavior.
