### ISSUE TITLE
Better handling of large combinatorial experiments

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#852]
Babysitting very large combinatorial simulations can be painful right now. If only some of the calculations fail for some reason (e.g., cluster problems), we can only do one of the following:
1. Restart every combinatorial experiment. This is currently slow because we need to load the full `ReplicaExchange` object from disk to determine whether a specific phase is completed or not.
2. For job arrays, we have to manually dig in the logs to find the jobid of the failed experiments and run only those. This is obviously not ideal.

I'd like to make two changes
1. Add a class method in `ReplicaExchange` (and relative instance method in `AlchemicalPhase`) to check the status of the calculations without loading the full `ReplicaExchange` object. Something like:
```python
class ReplicaExchangeStatus(typing.NamedTuple):
    """Status of the replica-exchange calculation"""
    number_of_iterations: int
    is_completed: bool

@classmethod
def get_status(cls, storage):
    """Read information about the status of the calculation from the storage file.

    Parameters
    ----------
    storage : str or Reporter
        The path to the storage file or the reporter object.

    Returns
    -------
    status : ReplicaExchangeStatus
        The status of the calculation.
    """
```
2. Resuscitate the `yank status` CLI argument (currently broken) to optionally take a YAML script as an input instead of the directory of a single experiment, and print status information for all experiments. The output would look like
```
yank status --yaml=yank.yaml
Total number of experiments: 155 (25 completed, 75 running, 55 pending)
```
or with verbose output
```
yank status --yaml=yank.yaml -v
experiment1:
    phase1: number_of_iterations=10000, status=completed
    phase2: number_of_iterations=10000, status=completed
...
experiment55:
    phase1: number_of_iterations=10000, status=completed
    phase2: number_of_iterations=2458, status=running
...
experiment124:
    phase1: status=pending
    phase2: status=pending
...
Total number of experiments: 155 (25 completed, 75 running, 55 pending)
```
I'd also add the argument `--status` to print only info about completed/running/pending experiments, and the argument `--njobs` to associate a `jobid` to the experiments, which can be helpful for array jobs.

I think this could save us a lot of troubles in the next couple of months. Objections? Thoughts?
