### ISSUE TITLE
Allow to specify the MultiStateSampler and MCMCMoves in the YAML script

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#898]
Picking up from the discussion in #863, what do you think about this?
```yaml
mcmc_moves:
    my-sequence-move:
        type: SequenceMove
        # Similarly to restraints, here go the __init__ arguments of the MCMCMove.
        move_list:
            - type: MCDisplacementMove
              # __init__ arguments of the nested MCMCMove.
              displacement_sigma: 1.5*nanometer
            - type: MCRotationMove
            - type: LangevinSplittingDynamicsMove
              n_steps: 500
              splitting: VRORV
    single-move:
        type: LangevinSplittingDynamicsMove
        timestep: 1.0*femtosecond

samplers:
    independent:
        type: MultiStateSampler
        # Here we can specify all the __init__ options.
        mcmc_moves: my-sequence-move
        number_of_iterations: 2000
        locality: 3
    repex:
        type: ReplicaExchangeSampler
        mcmc_moves: [single-move, single-move, my-sequence-move]
        number_of_iterations: 1000
        replica_mixing_scheme: swap-all
    sams:
        type: SAMSSampler
        state_update_scheme: local-jump

experiments:
    sampler: !Combinatorial [independent, repex]
    system: MySystem
    protocol: MyProtocol
    restraint: FlatBottom
```
I'd add the `samplers` and the `mcmc_moves` in two separate PRs (starting from the samplers).

I plan to set the defaults to use `ReplicaExchangeSampler` and 5000 iterations. Does this sound ok? Or do we want this to be a mandatory option?
