### ISSUE TITLE
AttributeError: module 'openmmtools.forces' has no attribute 'find_nonbonded_force'

### ISSUE THREAD

**Issue by isjoung** [choderalab/yank#935]
Hi,
I am trying to figure out how to calculate the binding free energy of a protein-ligand system using yank.
I encounter the following error after some force field initialization process. Could someone guide me in what to check to tackle the problem?

By the time of error, I got prmtop files, mol2 file and other coordinate files under my output directory. They look fine to me.
```
2018-03-29 17:36:27,564: Single node: executing <function ExperimentBuilder._check_resume at 0x7fcbf2764ea0>
2018-03-29 17:36:27,573: Running _setup_molecules serially.
2018-03-29 17:36:27,575: Running get_system serially.
2018-03-29 17:36:27,575: Running _generate_experiment_protocol serially.
2018-03-29 17:36:27,592: DSL string for the ligand: "resname STI"
2018-03-29 17:36:27,592: DSL string for the solvent: "auto"
2018-03-29 17:36:27,594: Reading phase complex
2018-03-29 17:36:27,594: prmtop: output/setup/systems/complex/complex.prmtop
2018-03-29 17:36:27,595: inpcrd: output/setup/systems/complex/complex.inpcrd
2018-03-29 17:36:42,187: ligand_atoms net charge: 1
2018-03-29 17:36:42,731: Ions net charges: [('Cl-', -1), ('Na+', 1), ('Na+', 1), ('Na+', 1), ('Na+', 1), ('Na+', 1), ('Na+', 1), ('Na+', 1), ('Na+', 1), ('Na+', 1)]
2018-03-29 17:36:42,731: Reading phase solvent
2018-03-29 17:36:42,732: prmtop: output/setup/systems/complex/solvent.prmtop
2018-03-29 17:36:42,732: inpcrd: output/setup/systems/complex/solvent.inpcrd
2018-03-29 17:36:45,313: solute_atoms net charge: 1
2018-03-29 17:36:45,384: Ions net charges: [('Cl-', -1)]
2018-03-29 17:36:45,385: Single node: executing <function ExperimentBuilder._save_analysis_script at 0x7fcbf27652f0>
2018-03-29 17:36:45,394: Initial checkpoint file automatically chosen as output/experiments/complex_checkpoint.nc
Traceback (most recent call last):
  File "/home/isjoung/miniconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.18.0', 'console_scripts', 'yank')()
  File "/home/isjoung/miniconda3/lib/python3.6/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/isjoung/miniconda3/lib/python3.6/site-packages/yank/commands/script.py", line 113, in dispatch
    yaml_builder.run_experiments()
  File "/home/isjoung/miniconda3/lib/python3.6/site-packages/yank/experiment.py", line 730, in run_experiments
    completed[exp_index] = self._run_experiment(exp)
  File "/home/isjoung/miniconda3/lib/python3.6/site-packages/yank/experiment.py", line 2325, in _run_experiment
    built_experiment.run(n_iterations=switch_experiment_interval)
  File "/home/isjoung/miniconda3/lib/python3.6/site-packages/yank/experiment.py", line 400, in run
    alchemical_phase = phase.initialize_alchemical_phase()
  File "/home/isjoung/miniconda3/lib/python3.6/site-packages/yank/experiment.py", line 279, in initialize_alchemical_phase
    alchemical_phase = self.create_alchemical_phase()
  File "/home/isjoung/miniconda3/lib/python3.6/site-packages/yank/experiment.py", line 265, in create_alchemical_phase
    **create_kwargs)
  File "/home/isjoung/miniconda3/lib/python3.6/site-packages/yank/yank.py", line 513, in create
    nonbonded_method = mmtools.forces.find_nonbonded_force(reference_system).getNonbondedMethod()
```

This is my yaml file.

```yaml
# Set the general options of our simulation
options:
  resume_setup: yes
  resume_simulation: yes
  minimize: yes
  verbose: yes
  number_of_iterations: 500
  temperature: 300*kelvin
  pressure: 1*atmosphere
  platform: CPU
  output_dir: output

# Configure the specific molecules we will use for our systems
molecules:
  protein:
    filepath: input/protein_amber.pdb
  ligand:
    filepath: input/ligand.mol2
    antechamber:
      charge_method: bcc
    leap:
      parameters: ['leaprc.gaff2']

# Define the solvent for our system
solvents:
  pme:
    nonbonded_method: PME
    nonbonded_cutoff: 9*angstroms
    clearance: 16*angstroms
    positive_ion: Na+
    negative_ion: Cl-

systems:
  complex:
    receptor: protein
    ligand: ligand
    solvent: pme
    leap:
      parameters: [leaprc.protein.ff14SB, leaprc.gaff2, leaprc.water.tip4pew]
    # When ligands are generated from SMILES they have a random position.
    # Setting "pack: yes" pulls the ligand close to the receptor ensuring
    # that your solvation box won't be too big.
    pack: no

protocols:
  absolute-binding:
    complex:
      alchemical_path:
        lambda_electrostatics: [1.00, 1.00, 1.00, 1.00, 1.00, 0.90, 0.80, 0.70, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.90, 0.80, 0.70, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]
        # Set lambda restraints reverse of coupling parameter.
        lambda_restraints:     [0.00, 0.25, 0.50, 0.75, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00]
    solvent:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.90, 0.80, 0.70, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.90, 0.80, 0.70, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]

# Here we combine the system and the protocol to make an experiment
experiments:
  system: complex
  protocol: absolute-binding
  restraint:
    type: Harmonic # Keep the ligand near the protein
```

This is the conda install list
```
# packages in environment at /home/isjoung/miniconda3:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.10           py36h306e16b_0
ambermini                 16.16.0                       7    omnia
asn1crypto                0.24.0                   py36_0
babel                     2.5.3                    py36_0
bleach                    2.1.3                    py36_0
bzip2                     1.0.6                h9a117a8_4
ca-certificates           2017.08.26           h1d4fec5_0
certifi                   2018.1.18                py36_0
cffi                      1.11.4           py36h9745a5d_0
chardet                   3.0.4            py36h0f667ec_1
clusterutils              0.3.1                    py36_0    omnia
conda                     4.4.10                   py36_0
conda-env                 2.6.0                h36134e3_1
cryptography              2.1.4            py36hd09be54_0
curl                      7.58.0               h84994c4_0
cycler                    0.10.0           py36h93f1223_0
cython                    0.27.3           py36h1860423_0
dbus                      1.12.2               hc3f9b76_1
decorator                 4.2.1                    py36_0
docopt                    0.6.2                    py36_1    omnia
docutils                  0.14             py36hb0f60f5_0
entrypoints               0.2.3            py36h1aec115_2
expat                     2.2.5                he0dffb1_0
fftw3f                    3.3.4                         2    omnia
fontconfig                2.12.6               h49f89f6_0
freetype                  2.8                  hab7d2ae_1
glib                      2.53.6               h5d9569c_2
gmp                       6.1.2                h6c8ec71_1
gst-plugins-base          1.12.4               h33fb286_0
gstreamer                 1.12.4               hb53b477_0
hdf4                      4.2.13               h3ca952b_2
hdf5                      1.10.1               h9caa474_1
html5lib                  1.0.1            py36h2f9c1c0_0
icu                       58.2                 h9c2bf20_1
idna                      2.6              py36h82fb2a8_1
imagesize                 1.0.0                    py36_0
intel-openmp              2018.0.0                      8
ipykernel                 4.8.2                    py36_0
ipython                   6.2.1            py36h88c514a_1
ipython_genutils          0.2.0            py36hb52b0d5_0
ipywidgets                7.1.2                    py36_0
jedi                      0.11.1                   py36_1
jinja2                    2.10             py36ha16c418_0
jpeg                      9b                   h024ee3a_2
jsonschema                2.6.0            py36h006f8b5_0
jupyter                   1.0.0                    py36_4
jupyter_client            5.2.3                    py36_0
jupyter_console           5.2.0            py36he59e554_1
jupyter_core              4.4.0            py36h7c827e3_0
kiwisolver                1.0.1            py36h764f252_0
latexcodec                1.0.1                    py36_0    omnia
libcurl                   7.58.0               h1ad7b7a_0
libedit                   3.1                  heed3624_0
libffi                    3.2.1                hd88cf55_4
libgcc                    7.2.0                h69d50b8_2
libgcc-ng                 7.2.0                h7cc24e2_2
libgfortran-ng            7.2.0                hdf63c60_3
libnetcdf                 4.4.1.1              h816af47_8
libpng                    1.6.34               hb9fc6fc_0
libsodium                 1.0.15               hf101ebd_0
libssh2                   1.8.0                h9cfc8f7_4
libstdcxx-ng              7.2.0                h7a57d05_2
libxcb                    1.12                 hcd93eb1_4
libxml2                   2.9.7                h26e45fe_0
lzo                       2.10                 h49e0be7_2
markupsafe                1.0              py36hd9260cd_1
matplotlib                2.2.2            py36h0e671d2_0
mdtraj                    1.9.1                    py36_0    omnia
mistune                   0.8.3                    py36_0
mkl                       2018.0.2                      1
mpi4py                    2.0.0                    py36_2    omnia
mpich                     3.2                           4    omnia
nbconvert                 5.3.1            py36hb41ffb7_0
nbformat                  4.4.0            py36h31c9010_0
ncurses                   6.0                  h9df7e31_2
netcdf4                   1.3.1            py36hfd655bd_2
notebook                  5.4.1                    py36_0
numexpr                   2.6.4            py36hc4a3f9a_0
numpy                     1.12.1           py36he24570b_1
numpydoc                  0.7.0            py36h18f165f_0
openmm                    7.2.1                    py36_1    omnia
openmmtools               0.15.0                   py36_0    omnia
openmoltools              0.8.3                    py36_0    omnia
openssl                   1.0.2n               hb7f436b_0
oset                      0.1.3                    py36_1    omnia
packaging                 17.1                     py36_0
pandas                    0.22.0           py36hf484d3e_0
pandoc                    1.19.2.1             hea2e7c5_1
pandocfilters             1.4.2            py36ha6701b7_1
parmed                    3.0.1                    py36_1    omnia
parso                     0.1.1            py36h35f843b_0
pcre                      8.41                 hc27e229_1
pexpect                   4.4.0                    py36_0
pickleshare               0.7.4            py36h63277f8_0
pip                       9.0.1            py36h6c6f9ce_4
prompt_toolkit            1.0.15           py36h17d85b1_0
ptyprocess                0.5.2            py36h69acd42_0
pybtex                    0.18                     py36_0    omnia
pybtex-docutils           0.2.1                    py36_1    omnia
pycosat                   0.6.3            py36h0a5515d_0
pycparser                 2.18             py36hf9f622e_1
pygments                  2.2.0            py36h0d3125c_0
pymbar                    3.0.1.beta0         np112py36_0    omnia
pyopenssl                 17.5.0           py36h20ba746_0
pyparsing                 2.2.0            py36hee85983_1
pyqt                      5.6.0            py36h0386399_5
pysocks                   1.6.7            py36hd97a5b1_1
pytables                  3.4.2            py36h3b5282a_2
python                    3.6.4                hc3d631a_1
python-dateutil           2.7.0                    py36_0
pytz                      2018.3                   py36_0
pyyaml                    3.12             py36hafb9ca4_1
pyzmq                     17.0.0           py36h14c3975_0
qt                        5.6.2               hd25b39d_14
qtconsole                 4.3.1            py36h8f73b5b_0
readline                  7.0                  ha6073c6_4
requests                  2.18.4           py36he2e5f8d_1
ruamel_yaml               0.15.35          py36h14c3975_1
schema                    0.6.2                    py36_0    omnia
scipy                     1.0.0            py36hbf646e7_0
send2trash                1.5.0                    py36_0
setuptools                38.4.0                   py36_0
simplegeneric             0.8.1                    py36_2
sip                       4.18.1           py36h51ed4ed_2
six                       1.11.0           py36h372c433_1
snowballstemmer           1.2.1            py36h6febd40_0
sphinx                    1.7.1                    py36_0
sphinxcontrib             1.0              py36h6d0f590_1
sphinxcontrib-bibtex      0.3.2                    py36_0    omnia
sphinxcontrib-websupport  1.0.1            py36hb5cb234_1
sqlite                    3.22.0               h1bed415_0
terminado                 0.8.1                    py36_1
testpath                  0.3.1            py36h8cadb63_0
tk                        8.6.7                hc745277_3
tornado                   5.0                      py36_0
traitlets                 4.3.2            py36h674d592_0
typing                    3.6.4                    py36_0
urllib3                   1.22             py36hbe7ace6_0
wcwidth                   0.1.7            py36hdf4376a_0
webencodings              0.5.1            py36h800622e_1
wheel                     0.30.0           py36hfd4bba0_1
widgetsnbextension        3.1.4                    py36_0
xz                        5.2.3                h55aa19d_2
yaml                      0.1.7                had09818_2
yank                      0.18.0                   py36_0    omnia
zeromq                    4.2.3                h439df22_3
zlib                      1.2.11               ha838bed_2
```
