### ISSUE TITLE
smiles: in molecules section of YAML no longer works

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#984]
The [documentation states that `smiles:` can be provided instead of `filepath:` in the `molecules:` section of the YAML](http://getyank.org/latest/yamlpages/molecules.html#smiles), but this seems to trigger an error:
```
lski2414:freesolv choderaj$ yank script --yaml=example.yaml
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/bin/yank", line 11, in <module>
    load_entry_point('yank==0.21.2', 'console_scripts', 'yank')()
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/yank/commands/script.py", line 133, in dispatch
    yaml_builder = ExperimentBuilder(script=yaml_path, job_id=job_id, n_jobs=n_jobs)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/yank/experiment.py", line 636, in __init__
    self.parse(script)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/yank/experiment.py", line 716, in parse
    yaml_content = self._expand_molecules(yaml_content)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/yank/experiment.py", line 1029, in _expand_molecules
    extension = os.path.splitext(comb_molecule['filepath'])[1][1:]  # remove dot
KeyError: 'filepath'
```
Here is the input YAML:
```yaml
---
# Set the general options of our simulation
options:
  minimize: yes
  verbose: yes
  temperature: 300*kelvin
  pressure: 1*atmosphere
  hydrogen_mass: 3*amu
  checkpoint_interval: 50

# Configure the specific molecules we will use for our systems
molecules:
  solutes:
    smiles: "CC(=O)O"
    antechamber:
      charge_method: bcc
    select: all

solvents:
  pme:
    nonbonded_method: PME
    nonbonded_cutoff: 9*angstroms
    clearance: 16*angstroms
  GBSA:
    nonbonded_method: NoCutoff
    implicit_solvent: OBC2
  vacuum:
    nonbonded_method: NoCutoff

systems:
  freesolv-hydration:
    solute: solutes
    solvent1: !Combinatorial [pme, GBSA]
    solvent2: vacuum
    leap:
      parameters: [leaprc.gaff, leaprc.protein.ff14SB, leaprc.water.tip4pew]

mcmc_moves:
    langevin:
        type: LangevinSplittingDynamicsMove
        timestep: 4.0*femtosecond
        splitting: VRORV
        n_steps: 2500

samplers:
    sams:
        type: SAMSSampler
        mcmc_moves: langevin
        state_update_scheme: global-jump
        gamma0: 10.0
        flatness_threshold: 1.0
        number_of_iterations: 500
        locality: 10

protocols:
  hydration-protocol:
    solvent1:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.04, 0.03, 0.02, 0.01, 0.00]
        lambda_torsions:       [1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
    solvent2:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.04, 0.03, 0.02, 0.01, 0.00]
        lambda_torsions:       [1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]

# Here we combine the system and the protocol to make an expirement
experiments:
  system: freesolv-hydration
  sampler: sams
  protocol: hydration-protocol
```
This error occurred with yank 0.21.2 on `osx`.
