### ISSUE TITLE
Water Hydration Free Energies

### ISSUE THREAD

**Issue by adw62** [choderalab/yank#994]
Hi, I'm trying to calculate some hydration free energies for different water models using YANK but am having some difficulty. I have tried to specify a single tip3p molecule (resname MOL) as the solute in a box of water molecules (resnames HOH). My vacuum system then has this PDB (tip3p.pdb):
```
CRYST1   30.000   30.000   30.000  90.00  90.00  90.00 P 1           1
ATOM      1  OM  MOL A   1       4.125  13.679  13.761  1.00  0.00
ATOM      2  H1M MOL A   1       4.025  14.428  14.348  1.00  0.00
ATOM      3  H2M MOL A   1       4.670  13.062  14.249  1.00  0.00
CONECT    1    2    3
CONECT    2    1
CONECT    3    1
END
```
and the hydrated system this PDB [boxofwater.txt](https://github.com/choderalab/yank/files/2019456/boxofwater.txt):
```
HEADER    Water Cubic Box (24.859 Ang, 512 TIP3P)
COMPND
SOURCE
CRYST1   24.859   24.859   24.859  90.00  90.00  90.00 P 1           1
HETATM    1  OM  MOL     1      -7.336   0.430   6.058
HETATM    2  H1M MOL     1      -7.789  -0.296   5.586
HETATM    3  H2M MOL     1      -6.850  -0.048   6.757
HETATM    4  O   HOH     2      -6.731  -0.274  -6.357
HETATM    5  H1  HOH     2      -6.426   0.649  -6.450
HETATM    6  H2  HOH     2      -7.442  -0.276  -7.022
…
CONECT 1534 1535 1536
CONECT 1535 1534
CONECT 1536 1534
END
```
both with this forcefield:
```
<ForceField>
 <AtomTypes>
  <Type name="tip3p-O" class="OW" element="O" mass="15.99943"/>
  <Type name="tip3p-H" class="HW" element="H" mass="1.007947"/>
  <Type name="tip4pew-M" class="MW" mass="0"/>
 </AtomTypes>
 <Residues>
  <Residue name="HOH">
   <Atom name="O" type="tip3p-O"/>
   <Atom name="H1" type="tip3p-H"/>
   <Atom name="H2" type="tip3p-H"/>
   <Atom name="M" type="tip4pew-M"/>
   <VirtualSite type="average3" siteName="M" atomName1="O" atomName2="H1" atomName3="H2" weight1="1.0" weight2="0" weight3="0"/>
   <Bond atomName1="O" atomName2="H1"/>
   <Bond atomName1="O" atomName2="H2"/>
  </Residue>
  <Residue name="MOL">
   <Atom name="OM" type="tip3p-O"/>
   <Atom name="H1M" type="tip3p-H"/>
   <Atom name="H2M" type="tip3p-H"/>
   <Bond atomName1="OM" atomName2="H1M"/>
   <Bond atomName1="OM" atomName2="H2M"/>
</Residue>
 </Residues>
 <HarmonicBondForce>
  <Bond class1="OW" class2="HW" length="0.09572" k="462750.4"/>
 </HarmonicBondForce>
 <HarmonicAngleForce>
  <Angle class1="HW" class2="OW" class3="HW" angle="1.82421813418" k="836.8"/>
 </HarmonicAngleForce>
 <NonbondedForce coulomb14scale="0.833333" lj14scale="0.5">
  <Atom type="tip3p-O" charge="-0.834" sigma="0.31507524065751241" epsilon="0.635968"/>
  <Atom type="tip3p-H" charge="0.417" sigma="1" epsilon="0"/>
  <Atom type="tip4pew-M" charge="0" sigma="1" epsilon="0"/>
 </NonbondedForce>
</ForceField>
```
I added a virtual site with no interactions to the HOHs so OpenMM can distinguish HOH from MOL but I think this should not change my answer.

I then make these into serialized OpenMM systems to be used by YANK. I think my problem is with my YAML file which looks like this:
```
options:
  minimize: yes
  verbose: yes
  output_dir: explicit
  temperature: 300*kelvin
  pressure: 1*atmosphere

systems:
  hydration-system:
    phase1_path: [boxofwater.pdb, SovSol.xml]
    phase2_path: [tip3p.pdb, Sol.xml]
    solvent_dsl: resname HOH

protocols:
  hydration-protocol:
    solvent1:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]
    solvent2:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]

experiments:
  system: hydration-system
  protocol: hydration-protocol
```
Here `phase1_path:` is the hydrated system and `phase2_path:` the vacuum system.

If I run this calculation it crashes for `phase2_path:` as I don't think I am setting it up correctly as a vacuum system and I get the attached error, [FE_error.txt](https://github.com/choderalab/yank/files/2019446/FE_error.txt), terminating with:
```
Exception: The periodic box size has decreased to less than twice the nonbonded cutoff.
```

Is there a way to declare the solvent in `phase2_path:` as vacuum? Or please let me know if there is anything else incorrect here.

Thank you,
Alex
